- PyPiDescription.rst
- README.md
- docker/README.md
* update tags in docker readme
* update conda binary names and pip repo names
> update instructions as per the latest public repos

- conda/.gitignore
- conda/README.md
- conda/build_packages.sh
- conda/torch-model-archiver/build.sh
- conda/torch-model-archiver/meta.yaml
- conda/torchserve/build.sh
- conda/torchserve/meta.yaml
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> conda: Add initial conda building scripts

- README.md
Fixes #246, a broken link for the model-archiver documentation
> fix model-archiver doc link

- README.md
I think some procedures are redundant and mistake
> Fix: document in README.md

- README.md
Updated installation instructions to include installing dependencies.
Fixes #278 
Fixes #242
- Logs
- [ X] Have you made corresponding changes to the documentation?
> documentation: updated installation instructions in README.md

- README.md
Changed ~ in paths in quick start steps to . 
Fixes #268 
- Logs
> documentation: changed home directory to current directory in paths

- README.md
This addresses path and navigation issues for the quick start, and adds Java SDK install steps for conda and install from source instructions.
Fixes #268 
- Logs
> documentation: fixed issues in installation and quick start in README.md

- README.md
Removing install of sentencepiece for now
Fixes #297
Doc change. Verified that instructions work on Ubuntu and Mac
> documentation: Reverting conda related doc changes from PR#286

- ci/buildspec.yml
- scripts/install_from_src_macos
- scripts/install_from_src_ubuntu
- scripts/install_utils
- torchserve_sanity.sh
This PR addresses following -
- Updated sanity script to use install_from_src_script for installing torchserve and model archiver
- created a utility script which contains all the common functions in one place
Fixes #334 
- Logs
> Updated sanity script to use install_from_src_ubuntu script

- docker/Dockerfile.gpu
The Dockerfile of GPU install package psutil duplicated.
Fixes 
Python package psutil install one time at Dockerfile.gpu
- [V] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Logs
> de-duplicate install package of psutil

- developing.md
We should have clearly documented steps for developers to contribute to TorchServe. This PR will serve as the test PR for creating this documentation flow.
Fixes #331 
- Logs
> Issue 331: Create developer documentation to contribute to TorchServe

- examples/image_classifier/mnist/README.md
- examples/image_classifier/resnet_152_batch/README.md
- examples/image_classifier/resnet_18/README.md
Corrected the steps in readme to create model 
Fixes # issue 324
Follow the steps in readme to create model resnet-152 
Result of test: resnet-152 model created
Result of test: mnist model created
Result of test: resnet-18 model created	
No code changed, only documentation change 
- Logs
> Corrected paths in commands given in readme

- scripts/install_from_src_macos
Fix typo in scripts/install_from_src_macos
Tested script on MacOSX
> Fix typo in scripts/install_from_src_macos

- test/README.md
- test/buildspec.yml
Final Fit & Finish changes for enabling Nightly Build
> Setup Nightly Build for TorchServe

- README.md
- docs/README.md
Adding missing document links to README
Fixes #296 #295 #259
> Adding missing document links to README

- examples/image_classifier/README.md
- examples/image_classifier/resnet_152_batch/README.md
- examples/image_classifier/resnet_18/README.md
> Rebase for #365

- test/postman/inference_data.json
- test/regression_tests.sh
Add test integration for Huggingface transformers examples.
Fixes #(issue)
Added integration tests.
- Logs
> Huggingface transformers integration test

- docker/README.md
Fixed broken links and made one of the steps for dev docker image explicit.
Fixes #399 
NA
NA
> Updated docker README.md

- README.md
- docker/Dockerfile.gpu
Merging Staging to Master for v0.0.1 release.
The only changes are README.md & Dockerfile.gpu both of which should be picked up from commit in master
> Merging Staging to Master for v0.0.1 release.

- benchmarks/README.md
- benchmarks/benchmark-ab.sh
Testing 
```
ubuntu@ip-172-31-78-248:~/bm/serve/benchmarks$ ./benchmark-ab.sh --model  vgg11 --url https://torchserve-mar-files.s3.amazonaws.com/vgg11.mar --bsize 1 --bdelay 50 --worker 4 --input ../examples/image_classifier/kitten.jpg --requests 20 --concurrency 10
TorchServe has stopped.
Preparing config...
starting torchserve...
Waiting for torchserve to start...
torchserve started successfully
Registering model ...
{
"status": "Workers scaled"
}
Executing Apache Bench tests ...
Executing inference performance test
Unregistering model ...
{
"status": "Model \"vgg11\" unregistered"
}
Execution completed
Grabing performance numbers
CPU/GPU: cpu
Model: vgg11
Concurrency: 10
Requests: 20
Model latency P50: 269.49
Model latency P90: 369.21
Model latency P99: 370.55
TS throughput: 12.57
TS …
```
> Apachebench benchmarking - Script / Documentation updates

- test/README.md
https://github.com/pytorch/serve/blob/nightly_build_flag_master/test/README.md
> Update code build flag to point to master

- docker/README.md
Update README for v0.1.1 for Docker
> Update Docker README for tags for v0.1.1

- README.md
- docs/configuration.md
Merging #413 from staging to master.
* Adding system diagram and brief explanation of workings
* Adding number of worker recommendations
* Adding description of netty configuration params
* Update header for worker threads readme section
Co-authored-by: mycpuorg <mail@mycpu.org>
Co-authored-by: dhanainme <60679183+dhanainme@users.noreply.github.com>
Fixes #(issue)
- …
> Adding system diagram and brief explanation of workings (#413)

- model-archiver.html
Replace existing model-archiver.html so that it renders properly
Fix to Issue: https://github.com/pytorch/serve/issues/490
Built locally:
> Replace new model-archiver.html file

- test/README.md
Build Badge / Logs for GPU Regression Tests
> Build Badge / Logs for GPU Regression Tests

- docs/torchserve_on_wsl.md
- added reference to know limitations for WSL from NVIDIA
- fixed in file link for `install from source`
Fixes #533 
NA
> added reference to known limitations for WSL from NVIDIA

- examples/image_classifier/README.md
Fix readme for examples/image_classifier
> Fix readme for examples/image_classifier

- docker/README.md
Readme file update, for smoother example run, added the step to retrieve the serialized model in `docker` folder.
Not applicable
Not applicable
> Updating docker section doc with a way to get serialized model

- test/postman/inference_data.json
Removed an erroneous line (seemed unintentionally added) from inference_data.json
As a result, the inference collection is now triggered for execution
Fixes #684
Executed following -
```
newman run -e postman/environment.json -x --verbose postman/inference_api_test_collection.json -d postman/increased_timeout_inference.json -r cli,html --reporter-html-export /tmp/report/inference_report.html
```
> Regression suite - Fix iteration data for inference collection 

- benchmarks/windows_install_dependencies.py
- examples/text_classification/README.md
- examples/text_to_speech_synthesizer/README.md
- examples/text_to_speech_synthesizer/create_mar.py
Fixes #582 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] This change requires a documentation update
[Examples.txt](https://github.com/pytorch/serve/files/5276136/Examples.txt)
[gradle_build_logs.txt](https://github.com/pytorch/serve/files/5276137/gradle_build_logs.txt)
[install_from_src.txt](https://github.com/pytorch/serve/files/5276138/install_from_src.txt)
[jmeter_logs.txt](https://github.com/pytorch/serve/files/5276139/jmeter_logs.txt)
[model_archiver.txt](https://github.com/pytorch/serve/files/5276140/model_archiver.txt) …
> Minor updates in example scripts for Win native support

- ts/torch_handler/text_handler.py
> Fixed typo.

- README.md
> fixed command for cuda101 specific binary installation

- kubernetes/README.md
Add troubleshooting scenarios and reorganize the troubleshooting section of the document.
Documentation change to add troubleshooting cases for the EKS setup.
Fixes #384 
N/A. Only a doc change.
> Add EKS troubleshooting steps

- README.md
- requirements/cpu.txt
- requirements/cuda101.txt
- requirements/cuda102.txt
- requirements/gpu.txt
- requirements_cuda101.txt
- requirements_cuda102.txt
- scripts/install_utils
- test/buildspec.yml
> Pt17 0 2 1

- frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelArchive.java
- frontend/server/src/main/java/org/pytorch/serve/ModelServer.java
- frontend/server/src/main/java/org/pytorch/serve/ensemble/Dag.java
- frontend/server/src/main/java/org/pytorch/serve/ensemble/Node.java
- frontend/server/src/main/java/org/pytorch/serve/ensemble/WorkFlow.java
- frontend/server/src/main/java/org/pytorch/serve/ensemble/WorkflowManifest.java
- frontend/server/src/main/java/org/pytorch/serve/ensemble/WorkflowModel.java
- frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
- frontend/server/src/test/java/org/pytorch/serve/EnsembleTest.java
- frontend/server/src/test/resources/workflow_handler.py
- frontend/server/src/test/resources/workflow_spec.yaml
> model registration

- kubernetes/kfserving/image_transformer/transformer.Dockerfile
- kubernetes/kfserving/kf_predictor_docker/Dockerfile_kf.dev
- kubernetes/kfserving/kf_predictor_docker/dockerd-entrypoint_kf.sh
- change docker file
- change entry point file
- change image transformer docker file
Fixes #(issue)
- Logs
> Fix: change kfserving docker image files

- kubernetes/kfserving/kf_predictor_docker/Dockerfile_kf.dev
Fix torchserve kfserving dockerfile
Fixes #(issue)
- Logs
> Fix: Update kfserving dockerfile

- test/regression_tests.py
Fixes #(issue)
issue847
- Logs
> add testing date time

- ts_scripts/sanity_utils.py
> changed link checker from error to warning

- frontend/gradle.properties
- plugins/gradle.properties
> [version_bump][0.0.4] 0.0.3->0.0.4

- docs/configuration.md
- docs/grpc_api.md
- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
- test/pytest/test_gRPC_utils.py
- ts_scripts/torchserve_grpc_client.py
> change grpc default ports to 7070 and 7071

- setup.py
This reverts commit dfab81394f991bb39df127cefd90a83a06d43156.
Fixes #(issue)
- Logs
> Revert "Add captum as dependency for TorchServe (#921)"

- docker/Dockerfile
Add captum as dependency for TorchServe docker image
```
./build_image.sh -bt production
docker run --rm -it -p 8080:8080 -p 8081:8081 pytorch/torchserve:latest-cpu
./build_image.sh -g -bt production
docker run --rm -it -p 8080:8080 -p 8081:8081 pytorch/torchserve:latest-gpu
```
```
curl -X POST "http://localhost:8081/models?initial_workers=1&synchronous=false&url=https://torchserve.pytorch.org/mar_files/mnist.mar"
curl http://localhost:8081/models/mnist
curl http://localhost:8080/predictions/mnist -T examples/image_classifier/mnist/test_data/0.jpg
curl -X DELETE http://localhost:8081/models/mnist
```
> Add captum as dependency for TorchServe docker image

- docs/inference_api.md
- examples/Huggingface_Transformers/README.md
- examples/image_classifier/mnist/README.md
- examples/text_classification/README.md
- kubernetes/kfserving/Huggingface_readme.md
- kubernetes/kfserving/README.md
- kubernetes/kfserving/mnist_readme.md
- kubernetes/kfserving/text_classifier_readme.md
Signed-off-by: Abishek Chiffon <abishekchiffon@gmail.com>
Modifications and clean ups on kfserving readmes and also added the kfserving APIs in the inference API readme
Fixes #(issue)
> Readme clean ups for KFserving apis 

- docker/Dockerfile
> refactored docker image to reduce size while running chown

- ts_scripts/install_dependencies.py
- ts_scripts/install_utils
> issue_1005

- ts_scripts/install_dependencies.py
> issue_1075

- examples/nmt_transformer/README.md
Add note about windows support for nmt example
> Add note about windows support for nmt example

- CONTRIBUTING.md
- README.md
- docker/README.md
- docker/build_image.sh
- docs/code_coverage.md
- requirements/torch_cu111_linux.txt
- requirements/torch_cu111_windows.txt
- test/benchmark/tests/utils/__init__.py
- ts_scripts/install_dependencies.py
> issue_1080

- docs/index.md
> Removed Experimental Flag from /docs/index.md

- examples/Workflows/README.md
Adding documentation for usage of same model in multiple workflows
Fixes #1124
Documentation update
> Adding documentation for usage of same model in multiple workflows

- kubernetes/kfserving/README.md
- kubernetes/kfserving/build_image.sh
Adds build script for Torchserve KFServing docker image building.
Fixes #1090
> feat: Add build script for kfserving torchserve image

- .gitignore
- docs/Troubleshooting.md
- docs/apis.rst
- docs/code_coverage.md
- docs/conf.py
- docs/contents.rst
- docs/custom_service.md
- docs/default_handlers.md
- docs/index.md
- docs/request_envelopes.md
- docs/torchserve_on_wsl.md
- docs/workflows.md
Initial design update to serve docs. Preview here: https://brianjo.github.io/serve/
Fixes #(issue)
Docs
N/A
> Updates serve doc TOC. 

- binaries/README.md
- binaries/conda/build_packages.py
- binaries/s3_binary_upload.py
- ci/torchserve_nightly_build.yml
Fixes #1178 
- Logs
```
(base) ubuntu@ip-172-31-38-29:~/serve/binaries$ python s3_binary_upload.py --s3-bucket s3://torchserve-nikhilsk-artifacts/pytorch/ --s3-backup-bucket s3://torchserve-nikhilsk-artifacts/pytorch-backup/ --nightly
S3 upload successful using command: aws s3 cp --recursive --exclude '*' --include '*.whl' …
```
> Add script to push nightly *.whl files to S3

- kubernetes/EKS/README.md
- kubernetes/EKS/templates/eks_cluster.yaml
Change node group to managed node group and set container runtime to Containerd
Fixes #580
> feat: k8s cluster creation

- frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
Logging null does not make sense.
Fixes #(issue)
- Logs
> Fix error message

- ci/launcher/launch_test.py
Fixes #(issue)
Fixes the following error on certain codebuild jobs which are triggered on 'PUSH' i.e. when a PR is commited. This error does not happen on a PR CI job itself:
```
Traceback (most recent call last):
File “/codebuild/output/src210026760/src/github.com/pytorch/serve/ci/launcher/launch_test.py”, line 188, in <module>
main()
File “/codebuild/output/src210026760/src/github.com/pytorch/serve/ci/launcher/launch_test.py”, line 184, in main
launch_ec2_instance(region, instance_type, ami_id)
File “/codebuild/output/src210026760/src/github.com/pytorch/serve/ci/launcher/launch_test.py”, line 77, in …
```
> GitHub hookshot fix

- ci/launcher/launch_test.py
Fixes the issue that output [link](https://serverlessrepo-github-codebuild-logs-cp-buildlogs-1hphnohzwif68.s3.amazonaws.com/f20c76da-ec39-414d-8ea8-bf1a3536f744/build.log?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAZFY6OBP57UB53UUU%2F20211105%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20211105T230044Z&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Security-Token=IQoJb3JpZ2luX2VjENf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJIMEYCIQCuCuaxuDEd4z%2FnRyTD4twNSwqRHU2byn8MfC3vvcxnMAIhAObk2rzsqe79INmo6hegi2yBTApKLbpRom1WvsABRXXsKswCCID%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEQARoMNjMwODg3MTU2NzMxIgwLweBxvgm49rbCsG8qoALJP …
> Set python io encoding to utf8

- ts_scripts/api_utils.py
> fix: revert kfv2 regression test changes

- test/buildspec.yml
Fixes #1370 
- Logs
Check this comment for verifying the correct status: https://github.com/pytorch/serve/pull/1377#issuecomment-996913965
> set fail for pipe in regression test

- ts/torch_handler/request_envelope/kfservingv2.py
Signed-off-by: jagadeesh <jagadeeshj@ideas2it.com>
Fixes #(issue)
- Logs
> fix: kfv2 service envelope for bytearray input

- ts/torch_handler/request_envelope/kserve.py
- ts/torch_handler/request_envelope/kservev2.py
Signed-off-by: jagadeesh <jagadeeshj@ideas2it.com>
Fixes #(issue)
- Logs
> fix: change log level to debug in kserve service envelope

- test/buildspec_gpu.yml
- test/buildspec_windows.yml
> update buildspec.yml for regression test

- test/buildspec_windows.yml
> remove cu102 since regression test win env is cpu

- ci/launcher/launch_test.py
Some CI build jobs time out / are flaky because the AMIs they use are older, and when running the 'apt-get update' command, the job takes a long time because of several pending updates.
Periodically updating the base AMI to the latest one shipped by AWS helps keep the number of updates minium, and improves success rate for the CI job.
- Logs
> Update CI to use latest Base DLAMI

- test/buildspec.yml
- test/buildspec_gpu.yml
Fixes incorrect type in yaml
```
[Container] 2022/02/21 15:49:57 CODEBUILD_SRC_DIR=/codebuild/output/src854226824/src/github.com/pytorch/serve
[Container] 2022/02/21 15:49:57 YAML location is /codebuild/output/src854226824/src/github.com/pytorch/serve/test/buildspec.yml
[Container] 2022/02/21 15:49:58 Phase complete: DOWNLOAD_SOURCE State: FAILED
[Container] 2022/02/21 15:49:58 Phase context status code: YAML_FILE_ERROR Message: Expected RuntimeVersions to be of map type: found list instead at line 8
```
Tested changes with codebuild
> Fix typo in regression test buildspec

- ts_scripts/install_dependencies.py
Update install dependencies script for regression testing. This installs the dev dependencies in appropriate order and the newer version of Nodejs required to run newman tests
Tested locally on codebuild with updated docker image
> Update install dependencies script for regression testing

- examples/image_classifier/alexnet/README.md
fix typo of examples/image_classifier/alexnet/README.md  #1462
Fixes #(issue)
- Logs
> fix: typo of examples/image_classifier/alexnet READE

- test/postman/kfv2_https_test_collection.json
- test/pytest/test_handler.py
Fixing MNIST path for kserve v1 and v2 regression tests.
Fixes #(issue)
- Logs
> [WIP] Kservev2 regression test fix

- test/postman/kfv2_https_test_collection.json
- test/pytest/test_handler.py
> Revert "[WIP] Kservev2 regression test fix"

- test/buildspec_gpu.yml
Fix gpu regression buildspec
Tested changes in codebuildonding changes to the documentation?
> Fix gpu regression buildspec

- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
- frontend/archive/src/test/java/org/pytorch/serve/archive/model/ModelArchiveTest.java
> check empty url

- docs/configuration.md
Delete duplicated explanation in configuration.md
Fixes #1547
> Remove duplicated docs in configuration.md

- .github/workflows/benchmark_nightly_cpu.yml
- .github/workflows/benchmark_nightly_gpu.yml
Increased timeout to 22h for nightly benchmarks
> increase timeout to 22h for benchmarks

- benchmarks/README.md
- benchmarks/jmeter.md
TODO
* Should we get rid of the `benchmarks/automated` folder to avoid confusion?
Followup PR
* Integrate torchprep guide
* Integrate performance guide
* Give more instructions related to sample yaml
* Provide instructions for pytorch profiler
FYI: @lxning
> update benchmark docs

- .github/workflows/benchmark_nightly_cpu.yml
- .github/workflows/benchmark_nightly_gpu.yml
remove _tool to make sure all dependencies are installed correctly.
https://github.com/pytorch/serve/actions/runs/2229647030/workflow
> Clean previous github run workspace

- ts/model_loader.py
Linted model_loader.py for issue https://github.com/pytorch/serve/issues/1595
> Add linting to ts/model_loader.py

- ts/model_service_worker.py
I've linted `ts/model_service_worker.py` as per issue [#1595](https://github.com/pytorch/serve/issues/1595).
> Linted `model_service_worker.py`

- ts/model_server.py
Linted model_server.py for issue #1595
> linted `model_server.py`

- ts/torch_handler/object_detector.py
Linted object_detector.py with black
Fixes #1595 
- [ X] Bug fix (non-breaking change which fixes an issue)
> #1595 linted object_detector with black

- docker/Dockerfile
> fixed typo in cuda docker installation

- examples/Huggingface_Transformers/Transformer_handler_generalized.py
Added linting to Transformer_handler_generalized.py
Fixes #1595
> Added linting to Transformer_handler_generalized

- binaries/README.md
- binaries/conda/README.md
- binaries/pip/README.md
- binaries/pip/retag_pypi_binary.sh
> Binary promotion instructions with nightly build setup

- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
- .github/workflows/lint.yml
- .github/workflows/torchserve-nightly-build.yml
This PR fixes a few quality of life issues I've seen new contributors run into with our Github Actions
1. When code isn't linted with `pre-commit` I now print in the Github Action what people need to do to unblock themselves
2. Made CI run on PR and not just push because otherwise PRs from forks do not run
3. Removed some debug logs from the nightly pypi torchserve workflow
Fixes #(issue)
This PR which is from `msaroufim:ghaqol` is now running all CI jobs https://github.com/pytorch/serve/pull/1705
This PR from a community …
> GHA QoL improvements

- docs/batch_inference_with_ts.md
Fix minor mistake in docs that is slightly confusing.
Not applicable
- [ x] Did you have fun?
- [ x] Have you made corresponding changes to the documentation?
> Move milliseconds from batch_size to batch_delay

- docs/README.md
> fix typo of "torchscripted"

- frontend/server/src/main/resources/proto/inference.proto
Fix a comment mistake, add comment to a RPC method.
Not needed
> Fix comment in inference.proto

- ts_scripts/utils.py
`check_python_version` has a wrong python version prompt.
Don't really think it need a ut
> update the error prompt in check_python_version

- frontend/server/src/main/java/org/pytorch/serve/util/codec/CodecUtils.java
This change simply adds more details into the error message to avoid confusion and suggest the fix
Fixes #1870
> "Add warning message for CorruptedFrameException (issue #1870)"

- cpp/src/backends/core/backend.hh
- cpp/src/backends/protocol/otf_message.cc
- cpp/src/backends/protocol/socket.cc
> Fix clang-tidy warnings

- .github/workflows/lint.yml
- ts_scripts/spellcheck.sh
Making same changes as #1919 to the lint workflow
Fixes #1918
CI Spellcheck successful
> Skip spellcheck section of lint if no changed files

- .github/workflows/ci-cpu-cpp.yml
Adds a bare minimum ci for cpp_backend branch. Runs `./build.sh` script.
> Add CI for cpp_backend branch

- .github/workflows/official_release.yml
- docker/build_upload_release.py
Minor fixes in the release script
Verified on my personal account
> Fixing minor issues in the release workflow

- test/pytest/conftest.py
Regression Tests were failing because the test suite was ignoring the previous file
Fixes #(issue)
> Fix for regression test suite failure

- test/pytest/test_onnx.py
Test was broken because `import torch` was in a try block and when onnx wasn't found, torch wasn't being installed either.
So the fix was just to move `torch` out and make sure `onnx` is not installed
Once that's done, the test gets correctly skipped
```
(noonnx) ubuntu@ip-172-31-17-70:~/serve/test/pytest$ pytest test_onnx.py 
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.8.13, pytest-7.2.0, pluggy-1.0.0
collected 5 items …
```
> Fix missing torch import in ONNX test

- .github/workflows/official_release.yml
Update java version to 17 in github actions for release
Fixes #(issue)
NA
> Updated java version to 17 in github actions for release

- .github/workflows/benchmark_nightly_cpu.yml
- .github/workflows/benchmark_nightly_gpu.yml
- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
- .github/workflows/doc-automation.yml
- .github/workflows/docker-nightly-build.yml
- .github/workflows/official_release.yml
- .github/workflows/torchserve-nightly-build.yml
Need to update github actions to use newer packages since node 12 is deprecated https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
Made the following changes to support node 16
- Updated setup-python version from v2 -> v4
- Updated checkout version from v2 -> v3
- Changed rishabhgupta/git-action-issue@v2 -> dacbd/create-issue-action@v1 
Fixes #([1977](https://github.com/pytorch/serve/issues/1977))
Run Docker nightly
-  ![Screen Shot 2022-11-17 at 11 19 15 …
> Update versions of setup-python, checkout and create-issue-action in github actions

- docs/configuration.md
> fix reponse timeout unit

- benchmarks/benchmark_config_gpu.yaml
- benchmarks/models_config/bert_multi_gpu_better_transformer.yaml
> add hg better transformer test

- cpp/build.sh
- cpp/src/backends/CMakeLists.txt
- cpp/src/examples/CMakeLists.txt
- cpp/src/examples/text_classifier/text_classifier_handler.cc
- cpp/src/examples/text_classifier/text_classifier_handler.hh
- cpp/test/CMakeLists.txt
- cpp/test/backends/torch_scripted/torch_scripted_backend_test.cc
- cpp/test/resources/torchscript_model/image_classification/base_handler/MAR-INF/MANIFEST.json
- cpp/test/resources/torchscript_model/image_classification/create_model.py
- cpp/test/resources/torchscript_model/text_classifier/create_bert.py
- cpp/test/resources/torchscript_model/text_classifier/test_input.txt
- cpp/test/resources/torchscript_model/text_classifier/text_classifier_handler/MAR-INF/MANIFEST.json
- examples/text_classification_with_scriptable_tokenizer/bert_example/README.md
- examples/text_classification_with_scriptable_tokenizer/bert_example/handler.py
Code changes based off of https://github.com/pytorch/serve/blob/feature/ts_backend_bert_example
Rebased on top of `cpp_backend` branch to include metrics implementation
Includes few fixes to the build
> CPP backend benchmark

- examples/Huggingface_Transformers/Transformer_handler_generalized.py
Replace 'palce' to 'place'
Just a little grammatical changes in thee hugging face example for transformers
Fixes #(issue)
No test required
> misspelled place

- benchmarks/benchmark_config_cpu.yaml
- benchmarks/benchmark_config_gpu.yaml
Remove workflow from benchmark since we already knew there are bugs in workflow.
Fixes #(issue)
> remove workflow from nightly benchmark

- README.md
Updating Walmart Blog Link
Fixes #(issue)
Documentation update
N/A
> updated walmart blog link

- requirements/common.txt
Fixes https://github.com/pytorch/serve/issues/2136
Fixes #(issue)
> Freeze pynvml version to avoid crash in nvgpu 

- .github/workflows/ci_cpu.yml
Upgrading CI CPU to run on Ubuntu 20.04
Fixes #([issue](https://github.com/pytorch/serve/issues/2152))
CI should pass
> upgrade CI to run on Ubuntu 20.04

- .github/workflows/regression_tests_cpu.yml
- .github/workflows/regression_tests_gpu.yml
We are close to the release and having a lot of commits.
Enabling tests to run daily
Fixes #(issue)
N/A
> Enable regression tests to run daily

- examples/pt2/README.md
explained right above but it is just misplaced
Fixes #(issue)
> move misplaced config-file arg from torchserve to torch-model-archiver

- torchserve_sanity.py
- ts_scripts/configs/sanity_models.json
- ts_scripts/marsgen.py
- ts_scripts/sanity_utils.py
Refactored torchserve sanity tests as preparation for pytest integration
Fixes #(issue)
> Refactor sanity tests

- kubernetes/AKS/README.md
Fix broken link
Fixes #(issue)
> fix broken link

- README.md
- ts_scripts/spellcheck_conf/wordlist.txt
Updating dead link
Fixes #(issue)
NA
> fix lint error

- docs/README.md
- docs/contents.rst
- docs/nvidia_mps.md
- docs/performance_guide.md
Update to mps.md to show images
Changed name of mps.md to nvidia_mps.md
Fixes #2541 
Built pages locally
> Update to mps.md

- kubernetes/kserve/kserve_wrapper/TorchserveModel.py
> fix response return type

- frontend/server/src/test/java/org/pytorch/serve/TestUtils.java
Solves https://github.com/pytorch/serve/security/code-scanning/10
> Default Hostname verifier in Test

- test/README.md
These are now on our main README.md
> Remove old test logs

- .github/workflows/lint.yml
This job has been very flaky it seems like doing so many network connections over so many commits is not working out
> disable flaky link checking

- ts_scripts/install_dependencies.py
Upgrades node version from 14 to 18 as 14 has been deprecated. 
Fixes #(issue)
> Update node version to 18

- .github/workflows/regression_tests_cpu_binaries.yml
- .github/workflows/regression_tests_gpu_binaries.yml
> disable these tests from getting executed in merge group

- requirements/torch_cu121_linux.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
PyTorch 2.1 release happened on Oct 4.
Updating the url to use the release wheels
Fixes #(issue)
> update test wheels with official 2.1 wheels

- examples/large_models/tp_llama/llama2.py
This PR fixes the flash attn by passing masks to avoid junk output.
Fixes #(issue)
[response](https://gist.github.com/HamidShojanazeri/01e5b03a19efc00c7ac52511b7ba7b70) after fixing the mask, 
[response](https://gist.github.com/HamidShojanazeri/cba001faa8471d81ba3032f42b30f703) before the fix
> fixing the falsh attn mask

- .github/workflows/regression_tests_gpu.yml
- requirements/torch_cu118_linux.txt
- requirements/torch_cu118_windows.txt
Update PyTorch version with CUDA 11.8
Fixes #(issue)
[regression-gpu - CUDA 118](https://github.com/pytorch/serve/files/12851383/1_regression-gpu.1.txt)
> update cu118 to use PT 2.1

- examples/pt2/README.md
Added some instructions for how to improve warm cache startup times for torch.compile
> Update cache info pt2

- .github/pytorch-probot.yml
Updated with the exact workflow names to be re-tried.
Docker regression runs were not re-tried last couple of days.
Fixes #(issue)
N/A
> Update which workflows need to be re-tried

- requirements/developer.txt
Changed `transformers` version to `>=4.34.0`
Fixes #(issue)
Regression Tests
> update transformers version to >= 4.34.0

- docs/batch_inference_with_ts.md
We updated the weights in the ResNet-152 batch model MAR file (please refer to this issue for more details: https://github.com/pytorch/serve/issues/2467).
With the updated MAR file, there are minor changes in the scores for each of the categories in the inference output. Creating this PR to update to the latest scores. 
Fixes #(issue)
Please describe the Unit or Integration tests that you ran to verify your changes and relevant result …
> Update inference output for ResNet-152 example

- frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelRequestEncoder.java
- frontend/server/src/main/java/org/pytorch/serve/util/messages/ModelInferenceRequest.java
- frontend/server/src/main/java/org/pytorch/serve/util/messages/RequestInput.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
- test/pytest/test_parallelism.py
This PR fixes tensor parallelism which was broken due to backend caching mechanism. It also introduces a simple test to detect this kind of issue in the future.
Fixes #(issue)
> Fix tensor parallelism

- .github/workflows/official_release_docker.yml
Bug fix for adding docker and kserve release to official_release env
Fixes #(issue)
N/A
> added docker/kserve release workflow to official-release env

- .github/workflows/regression_tests_gpu_binaries.yml
Fixed gpu nightly binary workflow for regression test
Succeeded run test:  https://github.com/pytorch/serve/actions/runs/6749178348
> Nightly GPU Binary workflow

- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
> fix writeandflush incomplete

- .github/workflows/benchmark_nightly.yml
Creating PR to deprecate inf1 nightly benchmarks.
Fixes #(issue)
> Deprecate inf1 nightly benchmarks

- .github/workflows/kserve_cpu_tests.yml
This fixes the nightly kserve tests by tagging v0.11.1 of kserve
Fixes #(issue)
- [Passing run](https://github.com/pytorch/serve/actions/runs/7174180906/job/19535253125)
> kserve nightly tests - Fix version of kserve

- cpp/src/backends/protocol/otf_message.cc
- cpp/src/backends/protocol/otf_message.hh
- cpp/src/backends/torch_scripted/handler/base_handler.cc
> merge cpp code from feature/cpp_backend_benchmark_lxning to cpp_revive3

- benchmarks/models_config/bert_torch_compile_gpu.yaml
- benchmarks/models_config/resnet50_torch_compile_gpu.yaml
- benchmarks/models_config/sam_fast_torch_compile_gpu.yaml
Creating this PR to remove CPU from the model configs for the torch.compile nightly benchmarks
> Remove CPU from model configs for torch.compile nightly benchmarks

- examples/Huggingface_Transformers/README.md
> Update README.md spelling error

- requirements/torch_cu118_linux.txt
- requirements/torch_cu118_windows.txt
- requirements/torch_cu121_linux.txt
- requirements/torch_cu121_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
Upgrade to PyTorch 2.2
Fixes #(issue)
Regression tests
> upgrade to PyTorch 2.2

- README.md
- benchmarks/README.md
- docs/Troubleshooting.md
- docs/performance_guide.md
- examples/pt2/torch_export_aot_compile/README.md
- ts_scripts/spellcheck_conf/wordlist.txt
Doc updates to fix broken links
Fixes #(issue)
> Documentation: fix dead links

- examples/pt2/torch_export_aot_compile/README.md
This PR updates pre-requisites for aot_compile to be PyTorch nightlies or 2.3
Fixes #(issue)
N/A
> Update PyTorch version in aot compile documentation

- .github/workflows/ci-cpu-cpp.yml
CI CPP is failing. 
This PR is disabling it from running on PRs.
Also enabling workflow dispatch
Fixes #(issue)
> enable workflow dispatch for CI CPP

- docs/token_authorization_api.md
Updating token documentation to add Maven link and setup documentation.
> Updating token documentation

- .github/workflows/torchserve-nightly-build.yml
Fixes #(issue)
- Before succeed nightly push
```
Run conda --version
conda 23.11.0
Requirement already satisfied: numpy in /usr/share/miniconda/lib/python3.11/site-packages (from captum==0.6.0->-r …
```
> pin python versin in conda in nightly push workflow

- .github/workflows/torchserve-nightly-build.yml
> pin python 3.9 in nightly push

- ts_scripts/install_dependencies.py
This PR fixes the installation of cpp dependencies
Fixes #(issue)
> Fix cpp dependencies installation

- .github/workflows/kubernetes_tests.yml
> correct typo in workflow file

- .github/workflows/official_release.yml
- .github/workflows/official_release_docker.yml
Changes needed to get the release workflow working
Fixes #(issue)
> Merge changes from Release 0.10.0

- SECURITY.md
> update email in security doc

- .github/workflows/ci_cpu.yml
- .github/workflows/regression_tests_cpu.yml
- .github/workflows/regression_tests_cpu_binaries.yml
Disabling tests on mac arm64 runners because of https://www.openwall.com/lists/oss-security/2024/03/29/4
Fixes #(issue)
> Disabling mac arm64 tests

- .github/workflows/doc-automation.yml
> Enable doc upload

- SECURITY.md
> fix grammer in security.md

- .github/ISSUE_TEMPLATE/bug.yml
> Fixed typo in bug issue template

- requirements/common.txt
- ts_scripts/install_dependencies.py
Pinning setuptools version due to newer version causing errors with pkg_resources
> Pinning setuptools version

- kubernetes/kserve/requirements.txt
> Revert "Kserve fix ray & setuptools dependency issue"

- requirements/developer.txt
> twine version update

- examples/pt2/torch_compile_hpu/README.md
I corrected the description of the example for HPU, where I added tokens to authorization and improved the process of installing torchserve.
> Adjust Resnet50 hpu example

- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
Reduce severity of xpu-smi logging to `Debug`.
Fixes #3236
> Reduce severity of xpu-smi logging

- .github/workflows/kserve_cpu_tests.yml
- kubernetes/kserve/requirements.txt
Fixes KServe build & Tests
Passing run: https://github.com/pytorch/serve/actions/runs/9964516723
Fixes #(issue)
> Bug fix for kserve build issue and fixing nightly tests

- SECURITY.md
Security doc update to add model API control
> Security doc update

- frontend/README.md
- ts_scripts/spellcheck_conf/wordlist.txt
This Pr adds some hints for java devs
Fixes #(issue)
> Add some hints for java devs

- examples/pt2/torch_export_aot_compile/resnet18_torch_export.py
- examples/text_classification/README.md
- examples/text_classification_with_scriptable_tokenizer/README.md
- requirements/torch_cu118_linux.txt
- requirements/torch_cu118_windows.txt
- requirements/torch_cu121_linux.txt
- requirements/torch_cu121_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_linux_aarch64.txt
- requirements/torch_windows.txt
- test/postman/inference_data.json
- ts_scripts/configs/sanity_models.json
This PR upgrades PyTorch to 2.4
- Removes TorchText dependency on CI
- Fixes aoti pytest for PT 2.4
- Deprecation warning for torchtext example
Fixes #([issue](https://github.com/pytorch/serve/issues/3066))
> upgrade to PyTorch 2.4

- .github/workflows/docker-ci.yaml
Corrects docker repo url by replacing git:// with https://
Fixes #(issue)
> Fix docker repo url in github action workflow

- .github/workflows/docker-ci.yaml
Fix branch/repo_url mixup
See run: https://github.com/pytorch/serve/actions/runs/10496096335/job/29075976668?pr=3294
See run: https://github.com/pytorch/serve/actions/runs/10496258432/job/29076501209?pr=3295
> Fix docker ci repo_url

- .github/workflows/docker-ci.yaml
> Remove debug step in docker ci

- README.md
This PR updates the quickstart llm docker deployment to the open ai api and adds an example which only uses ts.llm_launcher
> Update quickstart llm docker in serve/readme; added ts.llm_launcher example

- docker/Dockerfile
This PR fixes a situation where the fork we're trying to git clone from is not called serve.
Fixes #(issue)
> Fix Dockerfile fore renamed forks
