- examples/image_classifier/resnet_152_batch/resnet152_handler.py
The custom handler did not load the model on GPU. Even though the device is properly initialized with the gpu id, the model will always be loaded in the default device i.e., CPU.
Fixes #(153)
nvidia-smi output after registering the resnet152 model with 3 workers.
(torchserve38) ubuntu@ip-172-31-64-54:~$ nvidia-smi
Thu Apr 23 15:00:19 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.82       Driver Version: 440.82       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. | …
> fixed resnet152 custom handler to work with GPU

- README.md
Minor fix that removes a flag that doesn't work with pip.
However, I don't see why this is different from the regular installation steps that include many more dependencies. This fixes the current problem, but I still think this line should be reviewed.
Might be better to sync with:
```
pip install psutil future pytorch torchtext torchvision
```
Fixes #(issue)
Fixes #310 
- Logs
> remove minus y in pip install instructions

- scripts/install_from_src_macos
Fix for relative paths in install_from_src_macos script
Fixes #312
Validated by executing it in MacOS as 
./scripts/install_from_src_macos
NA
NA
NA
NA
> fix for macos script

- docker/README.md
Adds documentation for TS in Production env for Docker -  Shared Memory Size / User Limits for System Resources / Exposing specific ports / volumes between the host & docker env.
> Document the docker settings for running in production mode

- frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
- frontend/server/src/test/java/org/pytorch/serve/TestUtils.java
Made model server port tests independent of other test cases in ModelServerTest.java.
Fixes #391 
- Logs
[install_from_source_391.txt](https://github.com/pytorch/serve/files/4676837/install_from_source_391.txt)
> made model server port tests independent

- benchmarks/README.md
- benchmarks/install_dependencies.sh
- benchmarks/mac_install_dependencies.sh
- docker/README.md
- ts/model_service_worker.py
This PR addresses following :
- added code changes to enable backend profiling
- makes benchmark install dependency scripts independent of jmeter version.
Fixes #400
- create a docker image with BENCHMARK parameter set to true in model_service_worker.py
```
git clone https://github.com/pytorch/serve.git
cd serve
git checkout issue_400
cd docker
git clone https://github.com/pytorch/serve.git
cd serve
git checkout issue_400
vim ts/model_service_worker.py
cd ..
DOCKER_BUILDKIT=1 docker build --file Dockerfile_dev.cpu -t torchserve:dev .
```
- run benchmark's install_dependencies.sh
```
cd benchmark
./install_dependencies.sh
```
- start docker with /tmp directory mapped to local /tmp
```
docker run --rm -it -p 8080:8080 -p 8081:8081 -v /tmp:/tmp …
```
> added backend profiling and fixed benchmark's install dependency scripts

- docs/configuration.md
- frontend/server/src/main/java/org/pytorch/serve/ModelServer.java
- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
- frontend/server/src/main/java/org/pytorch/serve/util/codec/ModelRequestEncoder.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
- ts/model_server.py
- ts/model_service_worker.py
Adds an option to use [DirectBuffer](https://github.com/mrniko/netty-socketio/blob/bed2a3b05d68a5ac84eba32c59d410c0f88dc0d7/src/main/java/com/corundumstudio/socketio/Configuration.java#L347) for netty which is suitable for I/O instead of HeapBuffer
Closes #415
Verified UT/IT/ST. Stress tested with DirectBuffer
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
vmargs=-Xmx4g -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/log
prefer_direct_buffer=true
```
```
nohup ab -q -c 50 -n 1000000 -k -p sample_text.txt -T application/txt http://127.0.0.1:8082/predictions/BERT_SeqClassification > /tmp/buff.out 2>&1 &
```
> Porting memory fix changes to TorchServe

- .circleci/Dockerfile
- .circleci/config.yml
- .gitignore
Adds initial circleci configuration for building wheels.
Wheels will show up as build artifacts in circleci.
Runs `python setup.py bdist_wheel --release --universal` in CircelCI and then stores the artifacts for release.
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>
> .circleci: Add initial circleci configuration

- test/regression_tests.sh
Verified this on **nightly_code_build_branch_date_info** branch this info is added to the top of the log.
```
TS Branch :  nightly_code_build_branch_date_info
TS Branch Commit Id : 4ae2e8a5967eacf4212494c0e6964b9131bddb10
Build date :  Tue Jun 9 01:40:29 UTC 2020
newman
torchserve_regression_management
→ Register Model
POST http://localhost:8081/models?url=https://torchserve.s3.amazonaws.com/mar_files/squeezenet1_1.mar&model_name=squeezenet1_1 [200 OK, 409B, 903ms]
prepare   wait   dns-lookup   tcp-handshake   transfer-start   download   process   total 
22ms      6ms    170µs        846µs           886ms            8ms        540µs     924ms 
✓  Successful POST request
→ Get Valid Model
GET http://localhost:8081/models/squeezenet1_1 [200 OK, 584B, 8ms]
...
```
> Add build date / branch to nightly build

- benchmarks/benchmark-ab.sh
Fix typo ${WORKERS} -> ${WORKER} in the benchmark script to be able to set the number of initial workers correctly
> Fix typo in benchmark-ab.sh

- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkLoadManager.java
- frontend/server/src/test/java/org/pytorch/serve/SnapshotTest.java
Duplicate of https://github.com/pytorch/serve/pull/315 changed the base to master.
Snapshot not emitted after unregistering model with 0 workers
Fixes #200 
-[x] Test 1: No snapshot is created on list model request
(tsenv) admins@BRL07887:~TorchServe/TSSource$ curl "http://localhost:8081/models"
{
"models": []
}
(tsenv) admins@BRL07887:~$ ls logs/config/20200508164* -l
-rw-rw-r-- 1 admins admins 313 May  8 16:48 logs/config/20200508164820357-startup.cfg
-[x] Test 2: Snapshot is created when model is loaded with zero initial_workers
(tsenv) admins@BRL07887:~TorchServe/TSSource$  curl -X POST "http://localhost:8081/models?url=resnet-18.mar&initial_workers=0&synchronous=true"
{
"status": "Model \"resnet-18\" registered"
}
(tsenv) admins@BRL07887:~$ ls logs/config/20200508164* -l
-rw-rw-r-- 1 …
> Fixed issue Snapshot not emitted after unregistering model with 0 workers 

- ts/torch_handler/image_classifier.py
in image_classifier.py, when mapping of index to label is not defined, we should've done classes[index] instead of classes[i]. 'i' is not defined.
- Bug fix (non-breaking change which fixes an issue)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
> NameError fixed in default image_classifier.py torch handler

- ts/tests/unit_tests/test_beckend_metric.py
- ts/tests/unit_tests/test_worker_service.py
Updated backend test cases to make them compatible with pytest 6.0.0
Fixes #562
run backend pytest suite
```
pytest --cov-report html:htmlcov --cov=ts/ ts/tests/unit_tests/;
```
> updated backend test case to make them compatible with latest pytest version

- torchserve_sanity.sh
Reverted bert scripted models from sanity suite, which are currently broken on GPU (#479) . The sanity suite is currently passing on code build CI on GPU due to #564 
Hence reverting back the changes, these models should be added back in sanity suite as part of fix for #479 
Sanity suites executed successfully on CI build.
> removed bert scripted models from sanity script

- requirements/developer.txt
- test/regression_tests.sh
Pytest cases in regression suite fail on DLAMI due to incompatible pytest and numpy versions. Added numpy as dependecy package in `developer.txt` requirement file.
Fixes #606 
Regression suite execution log on DLAMI 30 :
[test_exec.log](https://github.com/pytorch/serve/files/5054876/test_exec.log)
> added numpy in developer requirement file

- frontend/modelarchive/src/main/java/org/pytorch/serve/archive/ModelArchive.java
- frontend/modelarchive/src/test/resources/models/noop_no_archive/noop/MAR-INF/MANIFEST.json
- frontend/modelarchive/src/test/resources/models/noop_no_archive/noop/service.py
- frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
- requirements/developer.txt
Torch Model Archiver has support for Model Archives as Naked dirs with the --archive-format "no-archive" - https://github.com/pytorch/serve/tree/master/model-archiver#arguments
However TS does not have a way to support these Naked Dirs. MMS has support for these. However support for this seems to have been dropped - https://github.com/awslabs/multi-model-server/blob/master/frontend/modelarchive/src/main/java/com/amazonaws/ml/mms/archive/ModelArchive.java
This PR adds support for Naked Dir and corresponding Model Server tests.
Support for Naked Dirs is key to integrating Torchserve with AWS Deep Learning container which are planned for this week release.
> Support for Naked Dir - no-archive Model Archives

- docker/Dockerfile
pip command requires `python3-distutils` package installed on linux. This package was missing in the Dockerfile.
Fixes #628
Logs on docker image created using Dockerfile from latest master :
```
(base) ubuntu@ip-172-31-54-27:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                              NAMES
e205f508e0bc        torchserve:latest   "/usr/local/bin/dock…"   38 seconds ago      Up 36 seconds       0.0.0.0:8080-8081->8080-8081/tcp   stoic_lumiere
(base) ubuntu@ip-172-31-54-27:~$ docker exec -it stoic_lumiere /bin/bash
model-server@e205f508e0bc:~$ pip show torchserve
Traceback (most recent call last):
File "/home/venv/bin/pip", line 7, in <module>
from pip …
```
> added python3-distutils in dockerfile

- model-archiver/model_archiver/model_packaging_utils.py
Now model_archiver uses fixed '/tmp' file dir as temporary files location. This is not laways true. This fix uses standard and secure way of working with temp files.
Run complete tes suite and integration tests.
- Logs
> Using python tempfile to handle security and non-standard temporary files

- model_zoo.html
I've enabled the models in the existing S3 bucket to be served on the torchserve.pytorch.org domain. It still points to the existing S3 bucket (torchserve.s3.amazonaws.com).
Fixes #(issue) - Not an existing issue
Use the new links for the models and verify that you are able to download them.
I was able to download the models from the new URL.
> Update model_zoo.html to with new URLs

- docker/README.md
Fix minor error in [docker/README.md](https://github.com/pytorch/serve/tree/master/docker#running-torchserve-in-a-production-docker-environment) as the '_Exposing specific ports / volumes between the host & docker env._' section specifies the option `-p8080:p8080 -p8081:8081` and it is not valid as there is an extra 'p' in `-p8080:p8080`, which may be confusing.
So the only fix has been `-p8080:p8080` to `-p8080:8080`.
> Fixed minor error regarding the Docker port option

- README.md
The README update to fix the broken link in Conda installation. Conda installation fails to install using:
`conda install torchserve torch-model-archiver`
This requires specifying the pytorch channel.
`conda install torchserve torch-model-archiver -c pytorch`
Fixes #(issue)
Conda installation using:
`conda install torchserve torch-model-archiver -c pytorch`
- Logs
[Torchserve_conda_installation_mac.logs.txt](https://github.com/pytorch/serve/files/5478002/Torchserve_conda_installation_mac.logs.txt)
[Torchserve_conda_installation.logs.txt](https://github.com/pytorch/serve/files/5478005/Torchserve_conda_installation.logs.txt)
> fixing the conda installation command by specifying the pytorch channel

- ts/torch_handler/unit_tests/test_image_classifier.py
- ts/torch_handler/unit_tests/test_image_segmenter.py
- ts/torch_handler/unit_tests/test_object_detector.py
- ts/torch_handler/unit_tests/test_utils/mock_context.py
Fixed Torch handler unit test attribute error - 'bytes' object has no attribute 'metrics'
Fixes #772 
Ran the run_script.sh from the ts/torch_handler/unit_test folder.
- Logs
[issue_772_run_scripts_logs.log](https://github.com/pytorch/serve/files/5488233/issue_772_run_scripts_logs.log)
> Fixes #772: unit test attribute error - 'bytes' object has no attribute 'metrics'

- ts_scripts/install_dependencies.py
- ts_scripts/mac_npm_deps
This fixes issue #842 regarding failure to install dependencies on Mac for source install
Fixes #842 
Bug fix (non-breaking change which fixes an issue)
The issue was that `node` was not installed in a path where `root` could see it, so calling `sudo npm install...` would fail. Trying without `sudo` failed because the `node_modules` folder was owned by `root`. This fix:
* Updates `ts_scripts/install_dependencies.py` to call `sudo ts_scripts/mac_npm_deps` instead of calling `sudo npm install...` directly
* Adds `ts_scripts/mac_npm_deps`, which does the following:
* Checks whether `node` is in the `PATH`
* If not, adjusts the path to include `/usr/local/bin`
* Checks for `node` again
* If `node` not available, exit with message
* Otherwise, perform `npm install...`
Tested Mac dependency …
> fix for issue 842

- test/postman/inference_data.json
Reverting failing regression test cases
Fixes Regression test failures
```
sudo rm /usr/local/cuda && sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda
ll /usr/local/cuda
ps ax|grep apt
git clone https://github.com/pytorch/serve/
cd serve/
git checkout build_fixes
python ts_scripts/install_dependencies.py --environment dev
python torchserve_sanity.py
python test/regression_tests.py
```
> Reverting failing regression test cases

- kubernetes/kfserving/README.md
When creating a Docker image that builds TorchServe from source, one needs at least 4GB of RAM allocated to the container. If too little RAM is allocated, OOMEs cause installation (specifically pip's installation of PyTorch, the package for which is >700MB) to fail with an uninformative error message ("Killed").
This PR adds a note to the documentation for setting up the KFServing Docker image recommending a 4GB minimum RAM allocation.
Fixes #860 
This change is a documentation update
The instructions to build the Docker image fail (on my Mac running macOS 10.15.7) if too little RAM is allocated, but succeed consistently when there's sufficient memory. This has been tested multiple times.
- n/a Have you added tests that prove your fix is effective or that this feature works?
- n/a New and …
> Doc fix for Issue 860, warn about OOME when building Docker image

- benchmarks/benchmark-ab.py
Fixes #876 - bad assumption about tmp path on Mac
- [√] Bug fix (non-breaking change which fixes an issue)
Issue was 100% failure; fixed path assumption, now runs correctly on Mac. Nothing changed for other envs.
- Logs
```
Generating Reports...
Writing extracted PredictionTime metrics to /var/folders/dz/74wm7dyd7_x4sc9q2fzm_h8dqwwlkh/T/benchmark/predict.txt
Writing extracted HandlerTime metrics to /var/folders/dz/74wm7dyd7_x4sc9q2fzm_h8dqwwlkh/T/benchmark/handler_time.txt
Writing extracted QueueTime metrics to /var/folders/dz/74wm7dyd7_x4sc9q2fzm_h8dqwwlkh/T/benchmark/waiting_time.txt
Writing extracted WorkerThreadTime metrics to /var/folders/dz/74wm7dyd7_x4sc9q2fzm_h8dqwwlkh/T/benchmark/worker_thread.txt
*Generating CSV output...
*Preparing …
```
> fixes issue 876 bad assumption about temp path

- README.md
Two links to the Window native documentation that don't get formatted correctly due to extra space in the beginning of lines.
Fixes #(issue)
Fixed the links and some minor typos.
> Formatting and typo fixes

- ts/torch_handler/vision_handler.py
The PR solve the issue #888 by converting the output of pre-process method in vision_handler to the current device.
Fixes #(issue)
converting the output of pre-process method in vision_handler to the current device.
Run the Mnist example with captum explanation. 
- Logs
The logs for failing and working status …
> convert the output of pre-process method to the current device

- ts/torch_handler/text_classifier.py
The issue is not filed and here is the explanation. The text classification example fails on explanations on GPU with the error that offsets are on cpu while required to be on GPU. This PR fixes the issue by converting offset in the text_classifier handler to the current device. This issue has caused the failure on running the this example through kfserving as well, logs are attached.
Fixes #(issue)
This PR fixes the issue by converting offset in the text_classifier handler to the current device.
- Logs
Here are the logs when it was failing and logs of the working example after the change. 
[text_classification_expalin_gpu_working.logs.txt](https://github.com/pytorch/serve/files/5691314/text_classification_expalin_gpu_working.logs.txt) …
> Text_classifier handler fix for expalantion on GPU 

- test/postman/kf_inference_data.json
This fixes the mnist failures that occurs in the mnist postman tests on windows.
- Logs
[windows_regression_logs.log](https://github.com/pytorch/serve/files/5702660/windows_regression_logs.log)
> Fixes mnist postman windows fail

- docker/Dockerfile.dev
- kubernetes/kfserving/kf_predictor_docker/Dockerfile_kf.dev
- requirements/torch_cpu.txt
- ts_scripts/install_dependencies.py
Added explicit cpu install dependency file
Fixes #912
```
> python ./ts_scripts/install_dependencies.py --cuda=cu101
> pip install -f https://download.pytorch.org/whl/test/torch_test.html torchserve torch-model-archiver
> pip freeze | grep torch
torch==1.7.1+cu101
torch-model-archiver==0.3.0
torchaudio==0.7.2
torchserve==0.3.0
torchtext==0.8.1
torchvision==0.8.2+cu101
> python ./ts_scripts/install_dependencies.py --cuda=latest
> pip install -f https://download.pytorch.org/whl/test/torch_test.html torchserve torch-model-archiver
> pip freeze | grep torch
torch==1.7.1
torch-model-archiver==0.3.0
torchaudio==0.7.2
torchserve==0.3.0
torchtext==0.8.1
torchvision==0.8.2
```
```
> python ./ts_scripts/install_dependencies.py
> pip install -f …
```
> Add CPU specific requirements file to install dependencies

- setup.py
Add captum as dependency for TorchServe
Tested on Linux/MacOS
```
python setup.py bdist_wheel --universal
pip install dist/torchserve-0.3.0b20201217-py2.py3-none-any.whl
```
> Add captum as dependency for TorchServe

- binaries/build.py
- binaries/conda/build_packages.py
- binaries/conda/torch-model-archiver/build.bat
- binaries/conda/torch-model-archiver/build.sh
- binaries/conda/torch-workflow-archiver/meta.yaml
- binaries/conda/torchserve/build.bat
- binaries/conda/torchserve/build.sh
- binaries/conda/torchserve/meta.yaml
Conda packages weren't actually getting created correctly, this should
resolve that issue by creating conda packages directly instead of basing
them on previously built wheel packages
Tested with:
```bash
❯ docker run --rm -i continuumio/miniconda3 <<-EOF
conda install -y python=3.7
conda install -y -c pytorch-test torch-model-archiver torch-workflow-archiver torchserve
EOF
...
environment location: /opt/conda
added / updated specs:
- torch-model-archiver
- torch-workflow-archiver
- torchserve
The following packages will be downloaded:
package                    |            build
---------------------------|-----------------
freetype-2.10.4            |       h5ab3b9f_0         596 KB
future-0.18.2              |           py37_1         631 KB
jpeg-9b                    | …
```
> binaries: Fix conda packaging process

- examples/Huggingface_Transformers/Download_Transformer_models.py
- examples/Huggingface_Transformers/README.md
- examples/Huggingface_Transformers/Transformer_handler_generalized.py
- examples/Huggingface_Transformers/model.py
This PR fix the issue #1137 and add back the commands for archiving Torchscript mode . Also, it fixes the initialize method to only move the model to device for eager mode as loading jit with map_location handle the device assignment for Torchscript.
Fixes #(issue)
#1137 
- To test the changes follow the readme for all models and modes. 
- Logs
Here are [logs](https://gist.github.com/HamidShojanazeri/f7a366fac78932fe0f5b83118a67d111) for Torchscript runs.
> Fixing issue #1137 and adding Torchscript archiving commands + fixing initialization for Torchscript models. 

- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
1. This change enables printing of error messages published to stdout or stderr by the 'python pip package installation' process.
2. It also corrects pythonPath used when installing a dependency package, while registering the model for the first time.
Fixes #1130 
- Logs
Following from issue #1130 , the following command succeeds:
```
torchserve --start --models iris=iris-new.mar --model-store ./benchmarks/model_store --ts-config ./benchmarks/model_store/config.properties 2>&1 > ~/torchserve.log
```
Caveat: …
> Correct pythonpath for pip dependency installation

- examples/text_to_speech_synthesizer/waveglow_handler.py
In the text_to_speech sample, the handler was likely copied from the image reco example first, so there were still comments in the preprocess function that indicated image processing, instead of text processing (which was actually happening). This fixes the comments. No change funcitonally. 
Fixes #(issue)
This is a surface level change to comments that were incorrect, no functional change required so did not run tests.
N/A: This is a surface level change to comments, no …
> fixing error in comment in text_to_speech_synthesizer handler

- frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
- frontend/server/src/test/java/org/pytorch/serve/SnapshotTest.java
- frontend/server/src/test/java/org/pytorch/serve/WorkflowTest.java
The frontend test unregistermodel uses sync mode. It takes about 5 min for this action. The fixing is using async mode to call unregistermodel and also guarantees the thread is terminated via countlatch.
Fixes #(issue)
#1306 
reduce frontend build from 20min to 5min 32s
- Logs
> optimize frontend build performance

- examples/MMF-activity-recognition/README.md
- test/pytest/test_handler.py
This PR skips the MMF pytest as it doesn't support PT 1.10 yet and adds the note to the doc.
- Logs
https://gist.github.com/HamidShojanazeri/49ac7a837e8b2ae8b548d1bd70191a8d
- [ X] Have you added tests that prove your fix is effective or that this feature works?
- [ X] Have you made corresponding changes to the documentation?
> Skipping mmf pytest as it doesn't support PT 1.10 

- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java
- ts/arg_parser.py
- ts/torch_handler/base_handler.py
- ts/torch_handler/unit_tests/test_mnist_kf.py
- ts/torch_handler/vision_handler.py
This PR will replace https://github.com/pytorch/serve/pull/1312/files
> add config option for ipex

- docs/inference_api.md
Fixes #(issue)
#1394 
curl http://localhost:8080/predictions/squeezenet1_1 -F ‘data=@docs/images/dogs-before.jpg’ -F ‘data=@docs/images/kitten_small.jpg’
{
“lynx”: 0.5370919704437256,
“tabby”: 0.28355872631073,
“Egyptian_cat”: 0.10669839382171631,
“tiger_cat”: 0.06301578134298325,
“leopard”: 0.006023887544870377
}
>>> import requests
>>> …
> update inference api doc

- benchmarks/automated/README.md
- benchmarks/automated/tests/suite/bert_cpu.yaml
- benchmarks/automated/tests/suite/bert_multi_gpu.yaml
- benchmarks/automated/tests/suite/fastrcnn.yaml
- benchmarks/automated/tests/suite/mnist.yaml
- benchmarks/automated/tests/suite/vgg11.yaml
- benchmarks/automated/tests/suite/vgg16.yaml
- benchmarks/automated/tests/utils/apache_bench.py
- benchmarks/automated/tests/utils/benchmark.py
- benchmarks/automated/tests/utils/cloudwatch.py
- benchmarks/automated/tests/utils/ts.py
- ci/benchmark/buildspec.yml
This PR adds support to publish metrics to cloudwatch, when the benchmark automated script is run. 
Trigger the benchmark run as follows:
1. Create an ec2 role with attached IAM role for permissions mentioned here: https://github.com/pytorch/serve/tree/master/benchmarks/automated
2. On the ec2 instance, clone this PR: 
`git clone https://www.github.com/pytorch/serve.git`
`cd serve`
`git fetch origin pull/1414/head:<BRANCHNAME>`, where <BRANCHNAME> is a branch of your choice.
3. `python benchmarks/automated/run_benchmark.py --run-only mnist 2>&1 | tee ~/logs/op_remote_mnist.log`
2. Check the cloudwatch metrics in AWS console to view the pushed metrics.
- Logs
> Add support to publish metrics to cloudwatch

- .github/workflows/nightly-build.yml
- setup.py
- ts_scripts/push_nightly.sh
Using this PR as a draft for Github Action nightly builds - does this work? I think the only missing thing is making sure if `ts_scripts/install_dependencies.py` is needed for the build @nskool 
Otherwise I can create a new project called `torchserve-nightly` on pypi and after I upload my personal access token we should be good to go? @seemethere 
repurposed the workflow here from @d4l3k  https://github.com/pytorch/torchx/blob/main/.github/workflows/nightly.yaml
TODO - can potentially do this in another PR
* Enable `DRY_RUN` by default
* Add last git hash to PKG_INFO
* Use github to publish artifacts
1. Run commands from github actions script one by one - the last one should print
```
(serve) ubuntu@ip-172-31-25-104:~/serve$ python setup.py --override-name torchserve-nightly bdist_wheel …
```
> Github Action Nightly Build

- .github/workflows/nightly-build.yml
Nightly build build fails right now when apt-get update is run because of a permission denied issue
So either we remove these two lines or add sudo - what do you think is best? @nskool 
Also I wonder how necessary this flag is for `install_dependencies.py` `--cuda=cu102` not sure how github actions plays with GPU runners
https://github.com/pytorch/serve/actions/runs/1852465948
> Update permissions on nightly-build.yml

- benchmarks/benchmark-ab.py
When running a benchmark with benchmark-ab.py script we run a warmup phase before benchmarking a model in the main stage. Part of the statistics collected for the report are extracted from the TorchServe log file. During this extraction we include the log lines from the warmup phase which dilutes the statistics (i.e. PredictionTime, HandlerTime, QueueTime, WorkerThreadTime) in the report. Due to this we systematically underestimate TorchServe's performance.
Additionally, this RP unbreaks benchmarkss/benchmark-ab.py which got broken due to a missing positional parameter (report_location) in a recent commit. A new …
> Remove logs from warm up period before calculating stats and unbreak bechmark-ab.py

- requirements/common.txt
- requirements/developer.txt
Fixes
for EC2 ubuntu base gpu torchserve fails to start due to missing nvgpu package
https://github.com/pytorch/serve/blob/ff4d90bfe18556739bee8465b83acb99f99be4a7/ts/metrics/system_metrics.py#L61
> added nvgpu to common dependencies

- docker/Dockerfile.dev
This PR moves the creation of the virtualenv to a place where we can change the owner to model-server without creating another layer. This ensures that users of the docker image can install packages without changing to root user.
Fixes #(issue)
#1499 
Build docker with: 
`./build_image.sh -bt dev`
Start docker:
docker run -ti --rm docker.io/pytorch/torchserve:dev-cpu bash
model-server@90d7c57df607:~$ ls -la /home/
total 16
drwxr-xr-x 1 root         root         4096 Mar 16 01:09 .
drwxr-xr-x 1 root         root         4096 Mar 16 …
> Make sure /home/venv is writeable by model-server user in dev docker image

- docs/inference_api.md
Signed-off-by: Abhay PS <psabhay@gmail.com>
In the docs, the inference API's ping response is not correct. Docs are now updated with the correct response of inference API's ping endpoint.
> Inference API ping response fixed

- docker/Dockerfile
When I was running ```./build_image.sh``` script, there was error like below.
```sh
sudo bash ./build_image.sh
[+] Building 1.2s (4/4) FINISHED                                                                                                                                                                                                        
=> [internal] load build definition from Dockerfile                                                                                                                                                                               0.0s
=> => transferring dockerfile: 38B …
```
> Update Dockerfile for Mising letter "\"

- ts/torch_handler/base_handler.py
To support old versions of torch <1.8.1, added an exception for importing `torch.profiler`.
Fixes #1548 
- Logs
> Add an exception for torch<1.8.1

- ts_scripts/install_dependencies.py
Predefined 'python' can be different from the command which is really executed.
So replace 'python' with sys.executable
Fixes #(issue)
> Use sys.executable instead of hard coding

- .github/workflows/doc-automation.yml
- docs/configuration.md
Issue: New doc build broken with unauthenticated git clone which is now deprecated https://github.com/pytorch/serve/actions/runs/2175184712
This PR fixes that issue and was tested and worked on my local fork https://github.com/msaroufim/serve/actions/runs/2186065934
Fixed the issue in upstream docs here https://github.com/pytorch/pytorch_sphinx_theme/pull/162
> Fix broken sphinx install for doc build

- .github/workflows/scale-config.yml
Added scale config to elastically use spare runners in case ours aren't enough
Note we should use the reserved instances first because this is elastic, a machine is requested which will cause the usual flakes when it comes to getting a GPU instance
> added scale config

- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
- torchserve_sanity.py
An end to end CI pipeline for Linux CPU and GPU, Mac and Windows using Github Actions - benefits are
* No need for sagemaker neo bot anymore
* No flakiness 
* Anyone can click on logs
* Can split logs in steps
* Nicer integration with Github CI
* Color highlighting and search in logs
* Easy retry functionality without empty PRs to trigger builds
* Added support for Mac, Linux and Window
Fixes #1568 
You can validate this works here https://github.com/pytorch/serve/runs/6089163894?check_suite_focus=true
> Migrate CI to Github Actions

- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
GPU and CPU CI now run concurrently so they disable each other depending on who runs last 
This fixes that issue
> fix cpu/gpu concurrency

- docker/build_image.sh
We were using an older version of cudnn in our `build_image.sh` which was causing
```
7 5.133 W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
#7 5.133 E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease' is not signed.
```
Fixes part 3 of #1621 - will address other issues in subsequent PRs
Please describe the tests [UT/IT] that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
Succesfully ran
``` …
```
> fixed nvidia key sign bug

- workflow-archiver/setup.py
```
run python  binaries/build.py
=>
./dist/torchserve-0.6.0-py2.py3-none-any.whl
./model-archiver/dist/torch_model_archiver-0.6.0-py2.py3-none-any.whl
./workflow-archiver/dist/torch_workflow_archiver-0.2.4b20220512-py2.py3-none-any.whl
```
```
run python  binaries/build.py
=>
./dist/torchserve-0.6.0-py2.py3-none-any.whl
./model-archiver/dist/torch_model_archiver-0.6.0-py2.py3-none-any.whl
./workflow-archiver/dist/torch_workflow_archiver-0.2.4-py2.py3-none-any.whl
```
> fix workflow archiver build version wrong

- docker/docker_nightly.py
Apologies for this fix,this was an extra commit I introduced after showing logs on the last PR 
Fixes https://github.com/pytorch/serve/actions/runs/2345149011
- https://github.com/pytorch/serve/actions/runs/2345149011
**Dry_run**
```
Executing command: ./build_image.sh -bt dev -t marksaroufim/torchserve-nightly:cpu-2022.05.18
Executing command: ./build_image.sh -bt dev -g -cv cu102 -t marksaroufim/torchserve-nightly:gpu-2022.05.18
Executing command: docker push marksaroufim/torchserve-nightly:cpu-2022.05.18
Executing command: docker push marksaroufim/torchserve-nightly:gpu-2022.05.18
Executing command: docker tag marksaroufim/torchserve-nightly:cpu-2022.05.18 marksaroufim/torchserve-nightly:latest-cpu
Executing command: docker tag marksaroufim/torchserve-nightly:gpu-2022.05.18 …
```
> Fixed typo in cuda version in docker_nightly.py

- frontend/gradle.properties
- frontend/server/src/main/java/org/pytorch/serve/workflow/WorkflowManager.java
- plugins/gradle.properties
- serving-sdk/pom.xml
Fixes #(issue)
https://github.com/pytorch/serve/security/dependabot/20
Please describe the tests [UT/IT] that you ran to verify your changes and relevant result summary. Provide instructions so it can be reproduced.
- Logs
[sanity.txt](https://github.com/pytorch/serve/files/8757923/sanity.txt)
> upgrade gson to 2.9.0

- test/buildspec_gpu.yml
[Nvidia error](https://github.com/NVIDIA/nvidia-docker/issues/1631) caused gpu regression test fail to download cuda.
```
Reading package lists…
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 InRelease: The following signatures couldn’t be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository ‘https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64 InRelease’ is no longer signed.
```
Fixes #(issue)
Please describe the tests [UT/IT] that you ran to verify your changes and …
> add workaround solution in gpu regression test

- frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
Fixes #(issue)
#1679 
Logs for Before: get "ready" even model is still in loading mode
curl http://localhost:8081/models/deeplabv3_resnet101_scripted
[
{ …
> fix describe worker state wrong

- docs/README.md
Fixes the `Encrypted model serving` link in [PyTorch website](https://pytorch.org/serve)
> fix: pytorch.org/serve encrypted model serving link

- README.md
- docs/management_api.md
Clarify Kserve protocol versions supported in Readme.
Clarify Kserve protocol versions supported by torchserve, in Readme
Fixes #1721
Not applicable.
Please let me know if it needs to be rephrased or documented differently,
Thanks.
> Clarify Kserve api in Readme 

- benchmarks/install_dependencies.sh
- docker/Dockerfile
- docker/Dockerfile.dev
- frontend/gradle/wrapper/gradle-wrapper.properties
- frontend/server/build.gradle
- ts_scripts/install_dependencies.py
- ts_scripts/install_utils
Upgrades java version to 17 on ubuntu.
One notable change is that `openjdk-17-jdk` instead of just headless package due to circular dependency issue with`ca-certificate-java` package. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009905. This increased docker image size by ~200MB.
Docker images sizes:
```
ubuntu@ip-172-31-37-107:~/torchserve$ docker images
REPOSITORY             TAG              IMAGE ID       CREATED       SIZE
pytorch/torchserve     prod-cpu-jdk17   1cabb0c21a26   11 days ago   1.98GB
pytorch/torchserve     prod-gpu-jdk11   c507dc722994   11 days ago   7.56GB
pytorch/torchserve     prod-cpu-jdk11   f77c9b66469c   12 days ago   1.54GB
pytorch/torchserve     dev-gpu-jdk11    cd68df3b8f75   12 days ago   10.5GB
pytorch/torchserve     prod-gpu-jdk17   8a0adb614cae   12 …
```
> Update java version to 17 on ubuntu

- requirements/developer.txt
Look at CI to see if this fix worked
When we merged the #1401 PR our Mac CI had bee flaky so we missed that `nvgpu` wouldn't be installed because no matching version of `ipex` would have been found for darwin.
See Mac CI below 
https://github.com/pytorch/serve/runs/7419700493?check_suite_focus=true
```
Requirement already satisfied: numpy in /Users/runner/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages (from -r requirements/common.txt (line 9)) (1.23.1)
Collecting nvgpu
Downloading …
```
> Don't install IPEX on Mac to unblock CI

- docs/sphinx/requirements.txt
Markdown 3.4 has made some breaking changes https://github.com/ryanfox/sphinx-markdown-tables/issues/36 which broke our doc build https://github.com/pytorch/serve/actions/workflows/doc-automation.yml so we right now we can't update our documentation
So suggestion for now is to pick an earlier version from https://github.com/ryanfox/sphinx-markdown-tables/issues/36
Fixes #1744 
About 7 different people have confirmed this works for them https://github.com/ryanfox/sphinx-markdown-tables/issues/36
> Pin markdown version to fix broken doc build

- ts_scripts/install_dependencies.py
- ts_scripts/install_utils
Update macOS java version to jdk 17. Previously, jdk11 from [adoptopen](https://adoptopenjdk.net/) was being used which does not have jdk17. Using [jdk17](https://formulae.brew.sh/formula/openjdk@17) from https://openjdk.org/ which is also consistent with Ubuntu.
Fixes #(issue)
Parent task : https://github.com/pytorch/serve/issues/1619
Sub task: https://github.com/pytorch/serve/issues/1731
[torchserve_sanity.log](https://github.com/pytorch/serve/files/9129133/torchserve_sanity.log)
[regression_tests.log](https://github.com/pytorch/serve/files/9129135/regression_tests.log)
[jdk17_mac_cpu_load_infer.log](https://github.com/pytorch/serve/files/9152264/jdk17_mac_cpu_load_infer.log)
```
(ts_py_env) nalrohit@147dda6964dd torchserve % java -version
openjdk version "17.0.3" 2022-04-19
OpenJDK …
```
> update java version to 17 on macOS

- .github/workflows/ci_cpu.yml
We only need to upload codecov for ubuntu for now so disabling mac and windows
Fixes #1757
> Skip codecov on Mac and Windows

- frontend/server/build.gradle
- frontend/tools/gradle/check.gradle
- plugins/tools/gradle/check.gradle
Updating to latest version of jacoco - 0.8.8 - https://www.eclemma.org/jacoco/ since there are codecov errors in ci log since jdk17 upgrade.
Ran `torchserve_sanity.py` locally and did not see the errors.
Also specified task dependencies to fix the warnings from gradle build.
e.g https://github.com/pytorch/serve/runs/7736904638?check_suite_focus=true
```> Task :server:processResources
Execution optimizations have been disabled for task ':server:processResources' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: '/home/runner/work/serve/serve/frontend/server/src/main/proto'. Reason: Task ':server:processResources' uses this output of task ':server:generateProto' without declaring an explicit or implicit dependency. This can lead to …
```
> update to latest version of jacoco

- .github/workflows/benchmark_nightly_cpu.yml
- .github/workflows/benchmark_nightly_gpu.yml
- CONTRIBUTING.md
This PR checks if the keyword at the top shows up anywhere in the PR description and if it does it triggers our benchmark suite. This is useful for times when you need to check if a given change improves performance or not without setting up a manual suite each time. Hopefully this will make it easier to easily measure and more quickly integrate performance related changes like #1631 and #1797 
Test is below
h/t @xuzhao9
> Trigger Benchmark using Keyword in PR

- .github/workflows/benchmark_nightly_cpu.yml
- .github/workflows/benchmark_nightly_gpu.yml
- CONTRIBUTING.md
- benchmarks/benchmark-ab.py
There is a failure in BenchMark CI https://github.com/pytorch/serve/actions/runs/2908587948
This happened because multiple instances of benchmark CI runs were running concurrently after the commit in PR 1798
Fixes #(issue)
Run benchmark CI on nightly basis only.
Also, added a None type check to avoid a crash.
- [ Yes] Have you made corresponding changes to the documentation?
> Temporarily reverting PR 1798 

- examples/intel_extension_for_pytorch/README.md
This PR updates examples/intel_extension_for_pytorch README -- fixes few typos, wordings, and updates IPEX int8 API
> updates examples/intel_extension_for_pytorch README

- ts/metrics/system_metrics.py
Fixes #1722 
I tested the solution on the non supported device. I can now run serve even if monitoring for the device is not supported.
> managing nvml exception

- .github/workflows/torchserve-nightly-build.yml
- binaries/conda/build_packages.py
Fixes #1821
`subprocess.run()` has frequently given me issues on Windows so changing back a single line back to `os.system()`
I temporarily enabled on push for nightly builds to test out on all 3 OSs at once
```
on:
push:
schedule:
- cron:  '15 11 * * *'
jobs:
```
https://github.com/pytorch/serve/runs/8090582952?check_suite_focus=true
> Fix Windows Nightly Build

- kubernetes/kserve/config.properties
- kubernetes/kserve/kserve_wrapper/TSModelRepository.py
- kubernetes/kserve/kserve_wrapper/TorchserveModel.py
- kubernetes/kserve/kserve_wrapper/__main__.py
Signed-off-by: jagadeesh <jagadeeshj@ideas2it.com>
fixes: [kserve/kserve-1915](https://github.com/kserve/kserve/issues/1915)
Issue: kserve model status API returns ready status only after a predict request as model is not loaded in startup.
Soln: Loads all TS models at start with `load_models` property and kserve load model method.
Gif of model status working after TS isvc deployment.
[model-status.log](https://github.com/pytorch/serve/files/9270878/model-status.log)
> fix: model status API for kserve

- ts/model_server.py
Fixes #1862 - There's an edge case where if `.model_server.pid` file is not deleted when torchserve stops abruptly and another process with same pid is started before torchserve is attempted to start again at which point it falsely assumes that the new pid of another process is torchserve process and exits with message `"TorchServe is already running, please use torchserve --stop to stop TorchServe."` This additional check validates that the process is actually a torchserve process and if not it will start torchserve. 
Testing:
* Usual path - verified that torchserve start and stop work as before
* Edge case path - manually changed the pid file to replace pid with another process and verified that torchserve started without complaining that torchserve is already running.
> Validate torchserve process in pid file before starting

- ts/metrics/system_metrics.py
Fixes #(issue)
#1881 
Only "import pynvml" in gpu host.
> fix pynvml import failure

- ts_scripts/spellcheck.sh
Skips spellcheck in CI if no changed files found
Fixes #1918
```
./ts_scripts/spellcheck.sh " "
++ sudo apt-get install aspell
Reading package lists... Done
Building dependency tree
Reading state information... Done
aspell is already the newest version (0.60.7~20110707-4ubuntu0.2).
The following packages were automatically installed and are no longer required:
linux-aws-5.4-headers-5.4.0-1075 linux-aws-5.4-headers-5.4.0-1078 …
```
> Skip spellcheck if no changed files

- benchmarks/utils/gen_metrics_json.py
BenchMark CI fails because the csv_dict has values which are neither int nor float. (Its am empty string in this case)
We end up calling float on this value and hence the script fails.
Fixes #(issue)
https://github.com/pytorch/serve/issues/1909
In `gen_metrics_from_csv`, change 
`if k in STATS_METRICS_CONFIG:`
to        
`if k in STATS_METRICS_CONFIG and isinstance(v, (int, float)):`
NA, not sure how to repro this
> Partial fix for benchmark ci failure

- cpp/build.sh
Install `clang-format` dependency on linux without which build fails with error:
`make: *** No rule to make target 'format'. Stop.`
> install clang-format on linux

- docker/build_image.sh
For CUDA 11.1,  only 11.1.1 Nvidia Docker images are available. Updated the script accordingly
Fixes #([1929](https://github.com/pytorch/serve/issues/1929))
- [Logs](https://github.com/pytorch/serve/files/9889911/serve_issues1929_logs.txt)
> For CUDA 11.1,  only 11.1.1 Nvidia Docker images are available.

- frontend/build.gradle
- frontend/tools/gradle/check.gradle
Fix gradle warnings as the following:
```
he RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.3/userguide/upgrading_version_6.html#jcenter_deprecation
at build_ensecnpt5e500c961c09u0g5y$_run_closure1$_closure3.doCall(/Volumes/workplace/python_env/serve/frontend/build.gradle:21 …
```
> fix gradle deprecation method

- test/pytest/test_handler.py
Reverts pytorch/serve#1924
This broke our regression tests, I'm suspecting there was an issue with needing to type in shell=True. Regardless no time to debug right now. The weird thing about this is it seems to unskip skipped tests like DLRM or real time video example and theb break them https://torchserve-regression-test.s3.amazonaws.com/public/latest/test_exec.log
Might make sense to move our regression tests to Github Actions so we can also get issue alerts when problems like this happen. I also believe we can just run regressions at least for GPU CI and detect lots of issues up front
> Revert "Replace os.system() calls with subprocess.run() in ./test/pytest/test_handler.py"

- .github/workflows/ci_cpu.yml
- .github/workflows/doc-automation.yml
- .github/workflows/docker-nightly-build.yml
- .github/workflows/lint.yml
- .github/workflows/official_release.yml
- .github/workflows/torchserve-nightly-build.yml
- docker/Dockerfile
- docker/Dockerfile.dev
- docker/Dockerfile.neuron.dev
- docker/build_image.sh
- kubernetes/kserve/Dockerfile.dev
Update default from Ubuntu 18.04 to Ubuntu 20.04 (LTS).
Fixes #1889 
I need advice on how to test the different updates.
Edit after comments:
> Update ubuntu docker version

- .github/workflows/regression_tests_cpu.yml
- .github/workflows/regression_tests_gpu.yml
- CONTRIBUTING.md
- benchmarks/auto_benchmark.py
- docker/README.md
- docker/build_image.sh
- docker/docker_nightly.py
- docs/code_coverage.md
- docs/getting_started.md
- requirements/torch_cu117_linux.txt
- requirements/torch_cu117_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
- test/pytest/test_onnx.py
- ts_scripts/install_dependencies.py
Upgrading PyTorch version to 1.13
- Added github actions for regression tests for CPU & GPU
Fixes #(issue)
> Upgrade to PyTorch 1.13

- requirements/common.txt
Fixes #(issue)
#2013 
pip list|grep -i yaml
WARNING: You are using pip version 20.2.3; however, version 22.3.1 is available.
You should consider upgrading via the …
> add pyyaml in requirements

- .github/workflows/official_release.yml
- docker/build_upload_release.py
Fixing the build script to build docker image with CUDA 11.7
Fixes #(issue)
[docker image details](https://hub.docker.com/layers/pytorch/torchserve/0.7.0-gpu/images/sha256-a8a5fb048b20fb71fed43d47caf370e5f4e15f27c219234734d8bb7d7870c158?context=explore)
> Fix docker build script to build with CUDA 11.7

- ts/torch_handler/base_handler.py
Fixes #2033 
I believe this error occured when I tried to merge the dynamo branch with the onnx branch since this line is no longer needed since eval happens directly if model is eager mode or ts
If the ONNX test was enabled by default we would have caught this when merging the torch.compile PR. 
In a follow-up PR I'm going to 
*  refactor the base handler a bit more 
*  Make all the optimization-related dependencies mandatory
*  Make our requirements.txt more modular
* Get back to doing releases with our non dev docker binaries
```
pip install onnx
(serve) ubuntu@ip-172-31-17-70:~/serve/test/pytest$ pytest test_onnx.py 
======================================================================== test session starts ========================================================================= …
```
> Remove bad eval when onnx session used

- docs/batch_inference_with_ts.md
> 8 is incorrect in batch_size, must use 3 instead

- .github/workflows/ci_cpu.yml
Downgrading CI to use ubuntu 18.04 as Ubuntu 20.04 CI has been flaky. 
- Upgrading to 22.04 did not resolve the issue
Fixes #([issue](https://github.com/pytorch/serve/issues/2053))
CI with 18.04 was reliable
> Downgrade CI to ubuntu 18.04 

- .github/workflows/benchmark_nightly_gpu.yml
We're ignoring the errors so it's not useful to keep having them
Should open a separate issue to figure out why this job is flaky
> Disable Alert on Nightly GPU

- kubernetes/kserve/Dockerfile.dev
Fixes #2075
Logs:
```bash
❯ DOCKER_BUILDKIT=1 docker build -f Dockerfile.dev -t pytorch/torchserve-kfs:latest-dev .
[+] Building 514.7s (14/17) …
```
> Update Dockerfile.dev to install gnupg before calling apt-key del 7fa2af80 (fix: #2075)

- benchmarks/install_dependencies.sh
- binaries/conda/torch-model-archiver/meta.yaml
- binaries/conda/torch-workflow-archiver/meta.yaml
- binaries/conda/torchserve/meta.yaml
- docs/torchserve_on_wsl.md
- frontend/archive/src/main/java/org/pytorch/serve/archive/model/Manifest.java
- frontend/server/src/main/java/org/pytorch/serve/ensemble/WorkflowManifest.java
- frontend/server/src/test/resources/management_open_api.json
- model-archiver/README.md
- model-archiver/model_archiver/manifest_components/manifest.py
- model-archiver/model_archiver/tests/pylintrc
- model-archiver/setup.py
- requirements/common.txt
- setup.py
- ts/tests/pylintrc
- ts_scripts/print_env_info.py
- ts_scripts/sanity_utils.py
- workflow-archiver/setup.py
- workflow-archiver/workflow_archiver/tests/pylintrc
Remove dependence on the `future` package and references to `Python2` in order to resolve security vulnerabilities.
Unregister `resnet-18` model after testing load from snapshot in sanity test to avoid subsequent sanity runs from failing.
Fixes #([2063](https://github.com/pytorch/serve/issues/2063))
CPU: [cpu_sanity_log.txt](https://github.com/pytorch/serve/files/10484508/cpu_sanity_log.txt)
GPU: [gpu_sanity_log.txt](https://github.com/pytorch/serve/files/10484510/gpu_sanity_log.txt)
CPU: [cpu_regression_log.txt](https://github.com/pytorch/serve/files/10484511/cpu_regression_log.txt)
GPU: [gpu_regression_log.txt](https://github.com/pytorch/serve/files/10484514/gpu_regression_log.txt)
CPU: [cpu_benchmark_log.txt](https://github.com/pytorch/serve/files/10484517/cpu_benchmark_log.txt)
GPU: …
> Deprecate future package and drop Python2 support

- examples/Huggingface_Largemodels/Readme.md
- examples/Huggingface_Largemodels/config.properties
- examples/Huggingface_Largemodels/custom_handler.py
fixing the missing steps on HF large model example
Fixes #(issue)
- [x ] This change requires a documentation update
> Hf large model doc fix

- docs/grpc_api.md
- ts_scripts/torchserve_grpc_client.py
Fixes #1852
I'm not able to register the `densenet161` model.  
When I run:
```python
python ts_scripts/torchserve_grpc_client.py register densenet161
```
I get: 
```
ModuleNotFoundError: No module named 'image_classifier'
````
Maybe related to #966. Is the handler in the mar ok? Can anybody help me on this error?
> Add argparse for grpc script

- .pre-commit-config.yaml
Bumps up isort version which fixes generation of pre-commit environment.
See https://github.com/home-assistant/core/issues/86892 for details
Fixes #(issue)
https://github.com/pytorch/serve/issues/2131
Run
```
pre-commit install
```
Create new commit
```
(ts3) ubuntu@ip-172-31-0-197:~/serve$ git commit -m "Bump isort dependency for pre-commit to 5.11.5"
Check python ast.....................................(no files to check)Skipped
Check builtin type constructor use...................(no files to check)Skipped …
```
> Fix pre-commit env creation by bumping up isort version

- .github/workflows/ci_gpu.yml
Noticed that CI GPU is still running on CUDA 10.2
Updating to CUDA 11.7
Fixes #(issue)
Check if CI GPU passes
> Update CI GPU to run on CUDA 11.7

- examples/text_classification_with_scriptable_tokenizer/handler.py
- examples/text_classification_with_scriptable_tokenizer/script_tokenizer_and_model.py
Enables the processing of multiple examples in one batch for the scriptable tokenizer example:
serve/examples/text_classification_with_scriptable_tokenizer
Fixes #(issue)
```
cd serve/examples/text_classification_with_scriptable_tokenizer
wget https://bert-mar-file.s3.us-west-2.amazonaws.com/text_classification_with_scriptable_tokenizer/model.pt
python script_tokenizer_and_model.py model.pt model_jit.pt
torch-model-archiver --model-name scriptable_tokenizer --version 1.0 --serialized-file model_jit.pt --handler handler.py …
```
> Enable batch processing in scriptable tokenizer example

- examples/README.md
- examples/image_classifier/mnist/README.md
- model-archiver/README.md
- model-archiver/model_archiver/arg_parser.py
This clears up existing references to "torch.nn.modules" and replaces them with "torch.nn.Module" with links to the docs as appropraite.
> Update model file docs to be more accurate

- model-archiver/model_archiver/model_packaging_utils.py
Fixes #2111 (Feature request)
**Implementation of wildcard filepaths for the model_archiver**
**Motivation**
"Large Language Models like Bloom, for example, consist of hundreds of sharded model files. Integrating all the model files as extra-files parameters is a cumbersome process. Wildcard support would help to solve this quickly."
**Implementation**
The change uses the same logic as before for how the extra_files are passed to the model archiver, but now also allows for passing wildcard paths like. /project/models/**.bin using the glob python module.
This does not require any new dependencies, but an update to the documentation is needed to inform about the new feature.
Running torchserve_sanity.py passes with no issues. The model_archiver …
> Wildcard search in model_archiver --extra-files 

- kubernetes/AKS/README.md
- kubernetes/GKE/README.md
Lint for dead link job is now red so fixing
> Fix Dead kubectl links

- model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py
- model-archiver/model_archiver/tests/unit_tests/test_version.py
So far tests for model-archiver had to be called from model-archiver folder. This PR changes this to make them callable from any folder.
The rest is just pre-commit beautification.
```
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.9.16, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/ubuntu/serve/model-archiver
plugins: mock-3.10.0, cov-4.0.0
collected …
```
> Make model-archiver tests runnable from any directory

- .github/workflows/regression_tests_cpu.yml
- .github/workflows/regression_tests_gpu.yml
- docker/README.md
- docker/build_image.sh
- docs/code_coverage.md
- docs/getting_started.md
- requirements/torch_cu117_linux.txt
- requirements/torch_cu117_windows.txt
- requirements/torch_cu118_linux.txt
- requirements/torch_cu118_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
- test/pytest/conftest.py
- ts_scripts/install_dependencies.py
- Upgrade to PyTorch 2.0
- TorchVision : 0.15.1
- TorchAudio:  2.0.1
- TorchText:     0.15.1
- Support for CUDA 11.8 . Default is CUDA 11.7
- Updated Regression tests to run once a week
Fixes #(issue)
- [regression-gpu (cu117).txt](https://github.com/pytorch/serve/files/11054475/1_regression-gpu.cu117.txt)
- [regression-gpu (cu118).txt](https://github.com/pytorch/serve/files/11054477/2_regression-gpu.cu118.txt)
- [regression-cpu (ubuntu-20.04).txt](https://github.com/pytorch/serve/files/11055031/1_regression-cpu.ubuntu-20.04. …
> Upgrade to PyTorch 2.0

- model-archiver/README.md
- model-archiver/model_archiver/arg_parser.py
- model-archiver/model_archiver/model_packaging_utils.py
- model-archiver/model_archiver/tests/conftest.py
- model-archiver/model_archiver/tests/integ_tests/configuration.json
- model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py
- model-archiver/model_archiver/tests/unit_tests/test_model_packaging_utils.py
This PR adds an option to our model-archiver tool to create a mar file without compression. This greatly speeds up the creation of the files which will enable us to reduce unit test time.
```
====================================================================== test session starts =======================================================================
platform linux -- Python 3.9.16, pytest-7.2.2, pluggy-1.0.0
rootdir: /home/ubuntu/serve/model-archiver
plugins: mock-3.10.0, cov-4.0.0
collected 29 items …
```
> Add zip-store option to model-archiver tool

- docs/contents.rst
- docs/index.md
- docs/mps.md
Adds NVIDIA MPS documentation to doc index
Fixes #(issue)
```
git clone https://github.com/pytorch/pytorch_sphinx_theme
pip install -e pytorch_sphinx_theme
pip install -r ./docs/sphinx/requirements.txt
cd docs/sphinx
make html
```
> Add NVIDIA MPS documentation to doc index

- docs/configuration.md
- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
- frontend/archive/src/test/java/org/pytorch/serve/archive/model/ModelConfigTest.java
- frontend/archive/src/test/resources/modelConfig/invalid.yaml
- frontend/archive/src/test/resources/modelConfig/valid.yaml
- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkLoadManager.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
- model-archiver/README.md
- ts/service.py
- ts_scripts/spellcheck_conf/wordlist.txt
- support torchrun parameters in model config yaml file.
- support gpu assignment "deviceIds" in model config yaml file.
- update doc about model config and gpu assignment algorithm.
- set torchrun log-dir under logs
Fixes #(issue)
#2207 
Please also list any relevant details for your …
> support torchrun and optimize gpu assignment

- test/pytest/test_sm_mme_requirements.py
- ts/model_service_worker.py
- ts/service.py
- ts_scripts/sanity_utils.py
Out sanity test output has about 1842833 lines (mainly through printing predictions) and is unusable for me in the browser.
This PR clips the output of predictions after 50 lines.
Fixes # None
```
| | |
V V V
```
> Make sanity test output useable again

- .gitignore
- test/pytest/test_data/torch_xla/compile.json
- test/pytest/test_data/torch_xla/config.properties
- test/pytest/test_data/torch_xla/model.py
- test/pytest/test_torch_xla.py
- ts/torch_handler/base_handler.py
- ts/utils/util.py
This PR is to add PyTorch/XLA support in TorchServe backend base handler.
> feat: add PyTorch/XLA support  

- docs/torchserve_on_win_native.md
> [easy] lint fix broken windows conda link

- docs/torchserve_on_win_native.md
Reverts pytorch/serve#2240
The original URL is working now. May be they changed something on their end.
> Revert "[easy] lint fix broken windows conda link"

- ts/torch_handler/base_handler.py
We are currently locked on an alpha version of torch 2.0.0. TorchServe (HEAD) was working for us before the PT2 refactor when the `base_handler` was deciding PT2, as below:
```
try:
import torch._dynamo
pt2_enabled = True
```
Creating a minor PR for enable torch2.0.0 alpha pre release to use torch.compile.
> Enable `torch.compile` support for torch 2.0.0 pre release

- .github/workflows/regression_tests_cpu.yml
- .github/workflows/regression_tests_gpu.yml
Reverts pytorch/serve#2248
These tests are not stable enough yet to alert regularly on
> Revert "open github issue on regression failure"

- requirements/developer.txt
Upgrade `transformers` package version to `4.28.1`
- CPU: [cpu_regression_log.txt](https://github.com/pytorch/serve/files/11408540/cpu_regression_log.txt) Pass
- GPU: [gpu_regression_log.txt](https://github.com/pytorch/serve/files/11408543/gpu_regression_log.txt)
- `test_sm_mme_requirements.py::test_oom_on_model_load` and `test_sm_mme_requirements.py::test_oom_on_invoke` fail. This is expected because of the different instance type the regression test was run on.
- CPU:
- `2023-05-05T17:20:44,927 [INFO ] W-9001-bert_1.0-stdout MODEL_LOG - This the output from the Seq classification model SequenceClassifierOutput(loss=None, logits=tensor([[ 0.5240, -0.4551]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)`
- `2023-05-05T17:20:44,927 [INFO ] W-9001-bert_1.0-stdout MODEL_LOG …
> Upgrade transformers version

- .github/workflows/benchmark_nightly.yml
- benchmarks/auto_benchmark.py
- benchmarks/benchmark_config_neuronx.yaml
- benchmarks/models_config/bert_neuronx.yaml
- examples/Huggingface_Transformers/Download_Transformer_models.py
- examples/Huggingface_Transformers/README.md
- ts_scripts/spellcheck_conf/wordlist.txt
Benchmark BERT model on Inferentia2 instance
Model artifacts:
- https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_1.mar
- https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_2.mar
- https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_4.mar
- https://torchserve.pytorch.org/mar_files/BERTSeqClassification_torchscript_neuronx_batch_8.mar
[Self hosted runner](https://github.com/pytorch/serve/settings/actions/runners/45)(inf2.8xlarge):
- 32 vCPUs
- 2 Inferentia2 chips (2 neuron cores per chip)
**Note: The artifacts above were traced using `transformers` version `4.19.0`. With more recent `transformers` versions, the traced model for Neuron may generate incorrect inference result. …
> BERT nightly benchmark on Inferentia2

- test/pytest/test_example_micro_batching.py
Fixes failing test for scriptable tokenizer
Fixes #(issue)
```
=========================================================================================================================================================================== test session starts ============================================================================================================================================================================
platform linux -- Python 3.8.16, pytest-7.3.1, pluggy-1.0.0 -- …
```
> Remove session_mocker usage to prevent test cross talking

- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java
- ts/model_service_worker.py
Fixes #(issue)
#2368 #2349 
- Test
torchserve --ncs --start --model-store model_store/ --models opt-30b-pippy.mar --ts-config benchmarks/config.properties
```config.properties
inference_address=http://0.0.0.0:8080 …
```
> fix tcp port in model_service_worker.py

- .github/workflows/regression_tests_gpu.yml
Regression GPU test queue is longer because we have to test cu117 and cu118.
We just need one version
Fixes #(issue)
> Remove cu118 from regression tests

- requirements/torch_cu117_linux.txt
- requirements/torch_cu117_windows.txt
- requirements/torch_cu118_linux.txt
- requirements/torch_cu118_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
Upgrade the following packages:
torch == 2.0.1
torchvision == 0.15.2
torchtext == 0.15.2
torchaudio == 2.0.2
> Upgrade PyTorch to 2.0.1

- test/pytest/test_utils.py
- ts/arg_parser.py
- ts/model_server.py
- ts_scripts/tsutils.py
This PR removes sleep(10) in our unit test utils and replaces it with a function which parses the log to wait the actual time it takes to start torchserve. This speeds up single unit tests by up to 4x.
Before:
After:
> Speed up unit tests by removing sleep in start/stop torchserve

- mypy.ini
- ts/model_server.py
- I included type annotations for the two functions in the file, I will continue to work on other files as I understand the returns and params.
Fixes part of #1512
**Completed mypy test stated on the issue.**
Logs for …
> Ts type annotations

- examples/large_models/inferentia2/Readme.md
- examples/large_models/inferentia2/inf2_handler.py
- examples/large_models/inferentia2/model-config.yaml
Fix handler for Inferentia2 example to handle partial batches and calls to `transformers-neuronx` library api
```
$ cat sample_text.txt 
Today the weather is really nice and I am planning on
$ curl http://127.0.0.1:8080/predictions/opt-125m -T sample_text.txt 
Today the weather is really nice and I am planning on
going through some camping next weekend. I thought if I didn’t
wear rain gear on Saturday maybe I would have to wear a coat but
I am using my wet shoes
```
```
$ cat sample_text.txt 
Today the weather is really nice and I am planning on
$ curl http://127.0.0.1:8080/predictions/opt-6.7b -T sample_text.txt 
Today the weather is really nice and I am planning on
spending the day in the park and riding my bike to the
store for ice cream. Then I will come home and study
more Spanish. …
```
> Fix INF2 example handler

- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
Fixes #(issue)
#2365 
- Test A: without model config yaml file.
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8082
metrics_address=http://0.0.0.0:8081
number_of_netty_threads=32 …
```
> fix: reflect model config in config.properties 

- frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
Fixes #(issue)
#2394 
- Test
```
cat model_store/mnist_scripted_v2/model-config.yaml
minWorkers: 1
maxWorkers: 1
batchSize: 8
maxBatchDelay: 400
deviceType: "cpu"
torchserve --start --ncs --model-store model_store/ …
```
> set device type as CPU

- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
Torchserve archiver add a root dir when it generates tgz archive format. For example.
```
torch-model-archiver --model-name mnist_scripted_v2 --version 2.0 --serialized-file mnist_script.pt --handler  mnist_handler.py --config-file model-config.yaml --archive-format tgz
=> mnist_scripted_v2.tar.gz
tar xvzf mnist_scripted_v2.tar.gz
=> mnist_scripted_v2
tree mnist_scripted_v2
mnist_scripted_v2
├── MAR-INF
│   └── MANIFEST.json
├── __pycache__
│   └── mnist_handler.cpython-38.pyc
├── …
```
> workaround solution for archiver tgz format on SageMaker

- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
- frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ArchiveUtils.java
- frontend/archive/src/main/java/org/pytorch/serve/archive/workflow/WorkflowArchive.java
- frontend/archive/src/test/java/org/pytorch/serve/archive/utils/ArchiveUtilsTest.java
- frontend/archive/testng.xml
- frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
Current implementation incorrectly interprets the model archive filename from the S3 presigned URL as follows:
S3 presigned URL: ```https://test-account.s3.us-west-2.amazonaws.com/mar_files/resnet-18.mar?response-content-disposition=inline&X-Amz-Security-Token=token&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230614T182131Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=credential&X-Amz-Signature=signature```
Interpreted model archive filename from URL: ```resnet-18.mar?response-content-disposition=inline&X-Amz-Security-Token=token&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20230614T182131Z&X-Amz-SignedHeaders=host&X-Amz-Expires=43200&X-Amz-Credential=credential&X-Amz-Signature=signature```
Expected model archive filename from URL: ```resnet-18.mar```
This causes the …
> Fix interpretation of filename from model archive URL

- docs/internals.md
- examples/instruction_embedding/README.md
- examples/instruction_embedding/instructor-embedding-handler.py
- examples/instruction_embedding/instructor_embedding_handler.py
- examples/instruction_embedding/requirements.txt
- ts_scripts/spellcheck_conf/wordlist.txt
A simple handler that one can use to serve [Instructor Embedding models](https://instructor-embedding.github.io/) with TorchServe, supporting both single inference and batch inference. Instructor Embedding models require both a sentence to embed as well as an instruction to contextualize the resultant embedding. Included in the PR is a README that shows how to serve Instruction Embedding models via `torchserve` as well as some example use cases.
Also in this PR is a simple documentation fix -- Fixed a strange anchor link in the documentation page about TorchServe's internals. Under the description of the different components of TorchServe's backend (Python), the link to `arg_parser.py` leads to a seemingly random line in the file _instead of_ the top line description of the file and the …
> Handler for Instruction Embedding models (and a typo fix)

- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
- frontend/build.gradle
- serving-sdk/pom.xml
- ts_scripts/install_dependencies.py
Sanity in CI currently fails with the following error:
```
A problem occurred evaluating project ':server'.
> Could not resolve all files for configuration ':server:runtimeClasspath'.
> Could not find org.pytorch:torchserve-plugins-sdk:0.0.4.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/pytorch/torchserve-plugins-sdk/0.0.4/torchserve-plugins-sdk-0.0.4.pom
- https://jcenter.bintray.com/org/pytorch/torchserve-plugins-sdk/0.0.4/torchserve-plugins-sdk-0.0.4.pom
Required by:
project :server
```
The `torchserve-plugins-sdk` artifacts are currently unavailable via JCenter or Maven Central repositories.
- Update the `distributionManagement` definition in `torchserve-plugins-sdk` `pom.xml` to point to Sonatype OSSRH repo.
- Update the `torchserve-plugins-sdk` …
> Publish torchserve-plugins-sdk artifacts to Maven Central repository

- docker/build_image.sh
Nightly docker builds are failing because NVIDIA has deprecated `nvidia/cuda:11.7.0-base-ubuntu20.04`
Updated to `nvidia/cuda:11.7.1-base-ubuntu20.04`
Fixes #([issue](https://github.com/pytorch/serve/issues/2439))
```
[+] Building 254.9s (24/24) FINISHED                                                                                                                                                      
=> [internal] load build definition from Dockerfile …
```
> Update nvidia base image version

- README.md
- examples/Huggingface_Transformers/README.md
This PR clarify the docs on the use of Flash attention and Xformer mem efficient kernels in Better Transformers/ Accelerated Transformers
Fixes #(issue)
- [ X] This change requires a documentation update
> update BT READMEs

- examples/torch_tensorrt/README.md
- examples/torch_tensorrt/requirements.txt
- examples/torch_tensorrt/resnet_tensorrt.py
- ts/torch_handler/base_handler.py
- ts_scripts/spellcheck_conf/wordlist.txt
This PR 
- Enables  Torch TensorRT to work without a custom handler  
- Example showing how to use Torch TensorRT with TorchServe
Fixes #([issue](https://github.com/pytorch/serve/issues/2482))
Before the fix
```
2023-07-19T21:15:42,182 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2023-07-19T21:15:42,234 [INFO ] main org.pytorch.serve.metrics.configuration.MetricConfiguration - Successfully loaded metrics configuration from /home/ubuntu/anaconda3/envs/torchserve/lib/python3.10/site-packages/ts/configs/metrics.yaml
2023-07-19T21:15:42,309 [INFO ] main org.pytorch.serve.ModelServer - 
Torchserve version: 0.8.1
TS Home: /home/ubuntu/anaconda3/envs/torchserve/lib/python3.10/site-packages
Current …
```
> Torch Tensor RT example

- CONTRIBUTING.md
- benchmarks/auto_benchmark.py
- docker/README.md
- docker/build_image.sh
- docker/build_upload_release.py
- docker/docker_nightly.py
- examples/pt2/README.md
Upgrade TorchServe to use CUDA 11.8 as default
Fixes #(issue)
- Auto-tested by Regression Tests
> Upgrade to use  CUDA 11.8

- .github/workflows/docker-nightly-build.yml
- .github/workflows/regression_tests_docker.yml
- docker/Dockerfile
- docker/README.md
- docker/build_image.sh
- docker/docker_nightly.py
Since we moved away from using Dockerfile.dev for production, Docker nightly builds are using the official version of TorchServe
This PR adds 
- an arg to docker script to build with torchserve nightly
- Changes docker regression scripts to use nightly
- This setups the infra to use PyTorch nightly for docker nightlies
Fixes #(issue)
```
(torchserve) ubuntu@ip-172-31-8-237:~/serve/docker$ ./build_image.sh  -bt ci  -t pytorch/torchserve:latest
[+] Building 185.9s (20/20) FINISHED …
```
> Added arg to build docker with torchserve nightly

- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
Fixes #(issue)
Corrected the documentation, it had to be "milliseconds" not "million seconds"
> Fixed typo in ModelConfig.java

- frontend/server/src/main/java/org/pytorch/serve/servingsdk/impl/ModelServerRequest.java
- frontend/server/src/test/java/org/pytorch/serve/util/PluginSdkTest.java
- frontend/server/testng.xml
Fixes `ModelServerRequest.getInputStream()` issue when the underlying buffer is a Netty direct buffer.
Fixes #2498 
[x] Bug fix (non-breaking change which fixes an issue)
Added a [simple test](./frontend/server/src/test/java/org/pytorch/serve/util/PluginSdkTest.java) for direct buffer write/read using SDK abstractions. 
Not sure if a new test suite is justified, would be happy to move elsewhere.
> Fix "direct buffer access" issue for Plugin SDK

- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
Issue warning about `allowed_urls` when default value is used.
The default value is `file://.*|http(s)?://.*`
Fixes #2531
- Without `allowed_urls` configured
```
$ torchserve --ncs --start --model-store model_store                                     
$ WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2023-08-22T11:29:05,267 [WARN ] main org.pytorch.serve.util.ConfigManager - Your torchserve instance can access any URL to load models. When deploying to production, make sure to limit the set of allowed_urls in config.properties
2023-08-22T11:29:05,271 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
..........
```
- With `allowed_urls` configured
```
$ cat custom_config.properties …
```
> Issue warning about allowed_urls when default value is used

- kubernetes/kserve/Dockerfile.dev
- kubernetes/kserve/kserve_wrapper/TorchserveModel.py
- kubernetes/kserve/requirements.txt
> fix kserve storage optional package

- ts/torch_handler/base_handler.py
Fixes a one-line syntax error in the base_handler initialize method, in the torch.compile section.
> Fix syntax error in base_handler initialize

- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelArchive.java
- frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ZipUtils.java
- frontend/server/src/main/java/org/pytorch/serve/util/messages/EnvironmentUtils.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerLifeCycle.java
Fixes #(issue)
#2454 
This is workaround solution to fix 3rd party dependency installation on SM. It always uses tmp dir to load model and install 3rd party dependency. If the model url is a dir, it creates a symbolic link under tmp to link with the url.
Please also list any relevant …
> always use tmp dir to load model

- mypy.ini
- ts/model_loader.py
- ts/model_service_worker.py
- ts/tests/unit_tests/test_model_service_worker.py
1. Adds necessary typehinting and checks for `None` to make `mypy` happy in two files: `ts/model_loader.py`, `ts/model_service_worker.py`
2. Adds unit test for `None` check in `handle_connection`
Related to #1512 
Code quality - typehints
See `ts/tests/unit_tests/test_model_service_worker.py`
> Typehints for model_loader and model_service_worker

- examples/image_classifier/resnet_18/README.md
Update example code for resnet18 model under image classifier. Fixed instructions so that code would work as explained. 
No need for unit tests as just documentation update. Previous documentation said if path is: /home/my_path/serve, run the steps from /home/my_path however the code `./examples/` will not work from /my_path. So documentation updated to run the steps from /home/my_path/serve which fixes this issue.
> fix example code for image classifier - resnet18 model

- .github/workflows/docker-nightly-build.yml
- kubernetes/kserve/build_image.sh
- kubernetes/kserve/docker_nightly.py
Workflow run: https://github.com/jagadeeshi2i/serve/actions/runs/6108738716/job/16578339051
Image Build logs: [torchserve-kfs-nightly.log](https://github.com/pytorch/serve/files/12559212/torchserve-kfs-nightly.log)
Fixes #(issue)
Please also list any relevant details for your test …
> add nightly build for torchserve-kfs image

- examples/large_models/deepspeed/Readme.md
Updating the README.md file for the DeepSpeed example. The example mentions the exact dependencies with which it has been tested.
Fixes #([issue](https://github.com/pytorch/serve/issues/2569))
Logs for …
> Update deepspeed example

- docs/README.md
- docs/model_loading.md
This is a guide for loading models in TorchServe
Main motivation was from the note by Hamel Husain https://hamel.dev/notes/serving/torchserve/
Fixes #(issue)
N/A
> A guide for loading models in TorchServe

- .github/workflows/regression_tests_gpu_binaries.yml
The GPU tests on self hosted runner don't work as expected.
Have spent half a day and not solved it completely
Disabling till I figure out the problem
Fixes #(issue)
> Disable GPU binaries test

- ts_scripts/install_dependencies.py
- ts_scripts/mac_npm_deps
newman published a new version yesterday, which started breaking our CI
https://www.npmjs.com/package/newman?activeTab=versions
Pinning the version to 5.3.2
This fixes mac regression issues
https://github.com/pytorch/serve/actions/runs/6201889968/job/16839506337
Fixes #(issue)
> pinning newman version to 5.3.2 as mac CI was flaky

- frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ZipUtils.java
Solves https://github.com/pytorch/serve/security/code-scanning/11
> Sha-256 in ziputils

- .github/workflows/ci_gpu.yml
- .github/workflows/regression_tests_gpu.yml
- CONTRIBUTING.md
- README.md
- benchmarks/auto_benchmark.py
- benchmarks/models_config/opt_6.7b_neuronx.yaml
- binaries/conda/build_packages.py
- docker/README.md
- docker/build_image.sh
- docker/build_upload_release.py
- docker/docker_nightly.py
- docs/code_coverage.md
- docs/getting_started.md
- requirements/torch_cu121_linux.txt
- requirements/torch_cu121_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
- ts_scripts/install_dependencies.py
Changes need to support PyTorch 2.1.0
- Includes support for CUDA 12.1 (Default version)
- Includes conda binary builds for python 3.11
- Docker builds with CUDA 12.1
- Updates to documentation
Fixes #(issue)
Passing CI/ Regression Runs
> Changes for PyTorch 2.1.0 and Python 3.11

- frontend/archive/src/main/java/org/pytorch/serve/archive/utils/ZipUtils.java
Fixes
https://github.com/pytorch/serve/security/code-scanning/14
https://github.com/pytorch/serve/security/code-scanning/2
> fix zip slip

- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkerThread.java
Solves https://github.com/pytorch/serve/security/code-scanning/4
> Use process build for GPU command

- frontend/server/src/main/java/org/pytorch/serve/http/HttpRequestHandlerChain.java
- frontend/server/src/main/java/org/pytorch/serve/job/RestJob.java
- frontend/server/src/main/java/org/pytorch/serve/util/NettyUtils.java
- frontend/server/src/main/java/org/pytorch/serve/workflow/WorkflowManager.java
Solves
https://github.com/pytorch/serve/security/code-scanning/5
https://github.com/pytorch/serve/security/code-scanning/6
https://github.com/pytorch/serve/security/code-scanning/8
https://github.com/pytorch/serve/security/code-scanning/9
> Enable Netty HTTP header validation

- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
Fixes
https://github.com/pytorch/serve/security/code-scanning/36
https://github.com/pytorch/serve/security/code-scanning/34
> Uncontrolled input fix for ModelManager

- benchmarks/benchmark-ab.py
- benchmarks/jmeter.md
- docker/README.md
- docker/start.sh
- docker/test_container_health.sh
- docker/test_container_model_prediction.sh
- docs/batch_inference_with_ts.md
- docs/use_cases.md
- examples/asr_rnnt_emformer/01_create_model_archive.sh
- examples/image_classifier/mnist/Docker.md
- frontend/server/src/main/java/org/pytorch/serve/util/NettyUtils.java
- frontend/tools/gradle/launcher.gradle
- test/pytest/test_data/torch_compile/config.properties
When starting torchserve inside a container, although the address configurations are set to `0.0.0.0` which is required to access torchserve from outside the container, access to torchserve in the container can be limited to localhost by binding the container ports to localhost ports as follows
**config.properties**
```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
model_store=/home/model-server/model-store
workflow_store=/home/model-server/wf-store
```
**Container ports not bound to localhost ports**
```
$ docker run --rm -it -p 8080:8080 -p 8081:8081 -p 8082:8082 pytorch/torchserve:latest-cpu
$ curl http://localhost:8080/ping
{
"status": "Healthy"
}
$ curl …
```
> Bind torchserve container ports to localhost ports

- .github/workflows/ci_gpu.yml
This PR cleans up the workspace directory fully from the CI GPU runners.
Fixes #(issue)
> Cleaning up previous runs from GPU runner

- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
- .github/workflows/codeql.yml
- .github/workflows/regression_tests_docker.yml
- .github/workflows/regression_tests_gpu.yml
If a CI has `workflow_dispatch:` that means you can manually trigger it from the Actions tab using your branch name. This is useful for example if we'd like to run code scanning on a PR without merging it to master first
This would also be ideal for running benchmarks but we'd need to then add an option to skip benchmark results upload to S3
> Manually Dispatch Most workflows

- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
Make sure 
- the process of pip installation runs under tmp dir
- the 3rd party package is installed under tmp dir
Fixes #(issue)
#2664 
> guard 3rd party package installation path

- SECURITY.md
Updates security guidelines to configure `allowed_urls` in production
Fixes #(issue)
N?A
> updating security documentation: allowed_urls

- examples/custom_metrics/README.md
- examples/custom_metrics/metrics.yaml
- ts/metrics/metric_abstract.py
- ts/tests/unit_tests/metrics_yaml_testing/metric_cache_unit_test.py
In `metric_abstract.py`, the `unit` attribute is not assigned if it is not one of the units defined in [unit.py](https://github.com/pytorch/serve/blob/master/ts/metrics/unit.py)
https://github.com/pytorch/serve/blob/0510772a8490fc3e3ea394c21d36858234900287/ts/metrics/metric_abstract.py#L43-L44
This can lead to the following error when attempting to emit the metric:
```
stdout MODEL_LOG - AttributeError: 'CachingMetric' object has no attribute 'unit'
```
Fixes #2637
Testing the following call to emit metric in handler code across different versions
```
self.context.metrics.add_metric('batchSize', len(data), 'request', dimensions=[Dimension(name="ModelName", value=self.context.model_name), Dimension(name="Level", value="Model")])
```
**v0.6.0**
```
2023-10-09T16:29:59,894 [INFO ] …
```
> Fix metric unit assignment

- .github/workflows/official_release.yml
- .github/workflows/official_release_docker.yml
- docker/build_upload_release.py
- docker/docker_nightly.py
- kubernetes/kserve/build_upload_release.py
- kubernetes/kserve/docker_nightly.py
This PR splits the official release workflow into 2 parts
- The original workflow will only publish binaries
- Added a second workflow for publishing docker images
- This is using the CI_GPU runner as self hosted runners have more disk space
-  This will also ensure that, we can publish docker images once we confirm that PyPI indices are updated with the latest version of TorchServe
Also changed the `docker push` commands to use `os.system` calls as we want this to execute first and be blocking.
Fixes #(issue)
[Test run of Docker workflow](https://github.com/pytorch/serve/actions/runs/6486104508/job/17613580328)
> Split official release workflow for binaries and docker

- benchmarks/config.properties
- benchmarks/config_template.properties
Update URLs in benchmark runs to use localhost
Fixes #(issue)
```
Starting AB benchmark suite...
Configured execution parameters are:
{'url': 'https://torchserve.pytorch.org/mar_files/mnist_v2.mar', 'gpus': 'all', 'exec_env': 'local', 'batch_size': 1, 'batch_delay': 100, 'workers': 4, 'concurrency': 10, 'requests': 500000, 'input': './examples/image_classifier/mnist/test_data/0.png', 'content_type': 'application/jpg', 'image': '', 'docker_runtime': '', 'backend_profiling': False, 'handler_profiling': False, 'generate_graphs': False, 'config_properties': './benchmarks/config.properties', 'inference_model_url': 'predictions/benchmark', 'report_location': '/tmp', 'tmp_dir': '/tmp', 'result_file': '/tmp/benchmark/result.txt', 'metric_log': …
```
> update URLs in benchmark tests to use localhost

- docker/build_upload_release.py
- kubernetes/kserve/build_upload_release.py
Based on the docker nightly run, https://github.com/pytorch/serve/actions/runs/6496259741
`subprocess.run` is confirmed to execute as a blocking call. The print statements were misleading.
So, replacing `os.system` with `subprocess.run`
Fixes #(issue)
Nightly docker build
> Docker official build workflow: replace os.system call with subprocess.run

- .github/workflows/regression_tests_docker.yml
It seems like we were not cleaning up the older images in the regression run correctly.
Fixes #(issue)
[Docker regression Run](https://github.com/pytorch/serve/actions/runs/6579846118)
> Changing the command to clean up docker images

- .github/workflows/regression_tests_cpu_binaries.yml
- .github/workflows/regression_tests_docker.yml
For Pytorch bot to retry a failed workflow, the retry is based on failure of a step.
Retry is skipped if the step name contains the word `test`
Fixes #(issue)
N/A
> remove keyword test from GH actions steps for pytorch bot

- .github/workflows/benchmark_nightly.yml
Inf2 benchmark runs have been failing for the last few days.
Disabling till issue is resolved.
Fixes #(issue)
N/A
> Disabling inf2 benchmarks as they are failing

- model-archiver/model_archiver/__init__.py
- model-archiver/model_archiver/arg_parser.py
- model-archiver/model_archiver/model_archiver.py
- model-archiver/model_archiver/model_archiver_config.py
- model-archiver/model_archiver/model_packaging.py
- model-archiver/model_archiver/model_packaging_utils.py
- model-archiver/model_archiver/tests/integ_tests/test_integration_model_archiver.py
- model-archiver/model_archiver/tests/unit_tests/test_model_archiver.py
- model-archiver/model_archiver/tests/unit_tests/test_model_packaging.py
- model-archiver/model_archiver/tests/unit_tests/test_model_packaging_utils.py
- test/pytest/test_auto_recover.py
- test/pytest/test_continuous_batching.py
- test/pytest/test_example_micro_batching.py
- test/pytest/test_example_near_real_time_video.py
- test/pytest/test_example_scriptable_tokenzier.py
- test/pytest/test_example_torchrec_dlrm.py
- test/pytest/test_parallelism.py
Adds a model archiver interface to archive models programmatically with a config class `ModelArchiverConfig` and an archiver class `ModelArchiver`. Simply wraps the existing CLI feature.
Fixes #2695 
As it's only wrapping the actual feature there's only a unit test very similar to the existing packaging test.
```bash
model_archiver/tests/unit_tests/test_model_archiver.py::TestModelArchiver::test_gen_model_archive PASSED                                                     [  3%]
```
```
model_archiver/tests/unit_tests/test_model_archiver.py::TestModelArchiver::test_model_archiver_config_from_args PASSED                                       [  6%]
```
> Model archiver api

- docker/Dockerfile
- docker/README.md
- docker/build_image.sh
- requirements/developer.txt
Fixes #(issue)
The following changes have been made in this PR:
- Moved the dev container stage to [Dockerfile](https://github.com/sachanub/serve/blob/master/docker/Dockerfile) from [Dockerfile.dev](https://github.com/sachanub/serve/blob/master/docker/Dockerfile.dev)
- While cloning the TorchServe repo in the Docker container, added the `--recursive` option to also pull the third party [googleapis](https://github.com/googleapis/googleapis) repository. If this is not done, running the …
> Update TorchServe dev container

- examples/Huggingface_Transformers/README.md
In the examples/Huggingface_Transformers Sequence Classification example, clarify that "Not Accepted" is a valid classification response, rather than a TorchServe error.
Fixes #1848
> Clarify that "Not Accepted" is a valid classification

- examples/pt2/README.md
- test/pytest/test_data/torch_compile/pt2_dict.yaml
- test/pytest/test_torch_compile.py
- ts/torch_handler/base_handler.py
Enables passing and arbitrary kwarg dict for torch.compile in BaseHandler, as discussed in issue #2783 .
Modified `test_torch_compile.py` to register 2 models:
- one configured with the backend as a str
- one configured with backend and mode in a dict
```
>> pytest serve/test/pytest/test_torch_compile.py
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.18, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/model-server/serve
collected 5 items
serve/test/pytest/test_torch_compile.py ..... …
```
> kwargs for torch.compile in BaseHandler

- docs/grpc_api.md
The current docs code only init the submodules but doesn't clone them. This change does both and bundles it into the main `git clone`.
> Fix gRPC docs to properly clone the git submodules

- docs/server.md
- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
- frontend/server/src/test/java/org/pytorch/serve/util/ConfigManagerTest.java
- frontend/server/src/test/resources/config_test_workflow.properties
- ts/model_server.py
https://github.com/pytorch/serve/issues/2792
Issue is that workflow store pathing in config.properties is being overwritten by the default workflow store location. 
Fixed this so that default path is only set if config.properties and cmd line are both empty. 
- **Test Case 1:**
- Created test in configManagerTest suite -  testWorkflowState()
- Checks if `getWorkflowStore()` returns the same path as provided in `config_test_env.properties`
- **Test Case 2:**
- Created test in configManagerTest suite - testNoWorkflowState
- Checks if `getWorkflowStore()` returns the default path (model_store path) since `config_test_workflow.properties` has no workflow_path
- **Test Case 3: added workflow_store path to config.properties and expect it to be used.**
config.properties:
```` …
```
> Fixed workflow store pathing issue #2792

- docker/Dockerfile
- docker/build_image.sh
`CUDA_VERSION` may be set in the container to the dot separated CUDA version number.  This conflicts with the docker build arg `CUDA_VERSION` used to select which CUDA version to use and results in an error like this when building the image:
```
....
[1/2] STEP 14/15: RUN     if echo "$BASE_IMAGE" | grep -q "cuda:"; then         if [ "$CUDA_VERSION" ]; then             python ./ts_scripts/install_dependencies.py --cuda $CUDA_VERSION;         else             python ./ts_scripts/install_dependencies.py;         fi;     else         python ./ts_scripts/install_dependencies.py;     fi
usage: install_dependencies.py [-h]
[--cuda {cu92,cu101,cu102,cu111,cu113,cu116,cu117,cu118,cu121}]
[--neuronx] [--environment {prod,dev}]
[--nightly_torch] [--force]
install_dependencies.py: error: argument …
```
> Fix CUDA_VERSION env var conflict

- kubernetes/kserve/build_image.sh
`docker/build_image.sh` creates a CPU image with tag 'latest-cpu'.  Use that tag when building the k8s kserve image.
Build several containers using this fix.
> Fix k8s image BASE_IMAGE

- examples/large_models/gpt_fast/README.md
- examples/large_models/gpt_fast/handler.py
- examples/large_models/gpt_fast/model_config.yaml
- examples/large_models/gpt_fast/model_config_speculative.yaml
- examples/large_models/gpt_fast/model_config_tp.yaml
- test/pytest/test_example_gpt_fast.py
- ts_scripts/spellcheck_conf/wordlist.txt
This PR adds tensor parallelism and speculative decoding to the GPT-fast example
Fixes #(issue)
```
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.3.0
plugins: mock-3.12.0, cov-4.1.0
collected 4 items / 3 deselected / 1 selected …
```
> Tensor parallelism for GPT fast example

- docs/metrics.md
- frontend/server/src/main/java/org/pytorch/serve/metrics/MetricBuilder.java
- frontend/server/src/test/java/org/pytorch/serve/metrics/MetricTest.java
- test/pytest/test_metrics.py
Add support for metrics legacy mode, where:
- `ts_inference_requests_total`, `ts_inference_latency_microseconds` and `ts_queue_latency_microseconds` are only available via the metrics API endpoint in prometheus format.
- All other metrics inclusive of auto detected backend metrics are only logged to `ts_metrics.log` and `model_metrics.log`
Fixes #2795 
```
$ cat examples/custom_metrics/config.properties 
metrics_mode=legacy
metrics_config=examples/custom_metrics/metrics.yaml
model_metrics_auto_detect=true
models={\
"mnist": {\
"1.0": {\
"defaultVersion": true,\
"marName": "mnist.mar",\
"minWorkers": 1,\
"maxWorkers": 1\
}\
}\
}
$ curl http://127.0.0.1:8080/predictions/mnist -T examples/image_classifier/mnist/test_data/0.png
0 …
```
> Add support for metrics legacy mode

- kubernetes/kserve/README.md
- kubernetes/kserve/kserve_wrapper/TorchserveModel.py
This PR enables kserve to work with model archiver folder along with .mar file
Fixes #([issue](https://github.com/pytorch/serve/issues/2830))
```
(torchserve) ubuntu@ip-172-31-60-100:~/serve/kubernetes/kserve$ git diff
diff --git a/kubernetes/kserve/kserve_wrapper/TorchserveModel.py b/kubernetes/kserve/kserve_wrapper/TorchserveModel.py
index 147d0a6a..528be615 100644
--- a/kubernetes/kserve/kserve_wrapper/TorchserveModel.py
+++ b/kubernetes/kserve/kserve_wrapper/TorchserveModel.py
@@ -1,5 +1,6 @@
""" The torchserve side …
```
> Changes to support no-archive  model archives with kserve

- .github/workflows/benchmark_torch_compile_nightly.yml
- benchmarks/auto_benchmark.py
- benchmarks/benchmark-ab.py
- benchmarks/benchmark_config_torch_compile_gpu.yaml
- benchmarks/models_config/bert_torch_compile_gpu.yaml
- benchmarks/models_config/resnet50_torch_compile_gpu.yaml
- benchmarks/models_config/vgg16_torch_compile_gpu.yaml
Creating PR to enable nightly benchmarks to compare torch.compile default mode and TorchScript for the following models:
- BERT Sequence Classification without Better Transformer. Please note that the BERT model artifacts will be updated again later to choose the one with the best performance (eg. with Better Transformer etc)
- VGG-16
- ResNet-50
Added new model artifacts for each of the above mentioned models:
- https://torchserve.pytorch.org/mar_files/bert-scripted.mar
- https://torchserve.pytorch.org/mar_files/bert-default.mar
- https://torchserve.pytorch.org/mar_files/vgg-16-scripted.mar 
- …
> Create nightly job for torch.compile benchmarks

- test/pytest/test_continuous_batching.py
This PR fixes a test related to continuous batching
Fixes #(issue)
```
============================================================================================================== warnings summary ==============================================================================================================
ts/torch_handler/base_handler.py:13
/home/ubuntu/serve/ts/torch_handler/base_handler.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
from …
```
> Fix continuous batching unit test

- benchmarks/benchmark-ab.py
- benchmarks/utils/gen_metrics_json.py
Creating PR to include queue time in the benchmark report.
Tests run:
Ran benchmark locally with `resnet50.yaml` with batch sizes 1, 2, 4, 8, 16 and concurrency 4. 10000 requests are used for inference. 
```
---
---
resnet50:
scripted_mode:
benchmark_engine: "ab"
url: "file:///home/model-server/torch_compile_ab_benchmarks/resnet50/resnet-50-scripted.mar"
workers:
- 4
batch_delay: 100
batch_size:
- 1
- 2
- 4
- 8
- 16
requests: 10000
concurrency: 100
input: "/serve/examples/image_classifier/kitten.jpg"
handler_profiling: True
backend_profiling: True
exec_env: "local"
processors:
- "cpu"
- "gpus": "all"
```
The AB report and metrics can be found be in …
> Include queue time in benchmark report

- frontend/server/src/main/java/org/pytorch/serve/http/messages/RegisterModelRequest.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/ModelManager.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/WorkLoadManager.java
- requirements/developer.txt
- test/pytest/test_model_config.py
- test/pytest/test_utils.py
Fixes #(issue)
#2851 
Except regression test, a manual test for GPU deviceIds is added b/w it requires multi-GPU host.
- model-config.yaml
```
cat model_store/mnist/model-config.yaml
minWorkers: 4
maxWorkers: 4 …
```
> Fixed the priority of parameters  defined in register curl cmd vs model-config.yaml

- test/pytest/test_model_config.py
Disabling the test test_register_model_with_batch_size since this seems flaky on regression runs on GPU
Passing run
```
pytest -v test_model_config.py 
================================================================================== test session starts ===================================================================================
platform linux -- Python 3.10.0, pytest-7.3.1, pluggy-1.0.0 -- /home/ubuntu/anaconda3/envs/ts_aot_compile/bin/python
cachedir: .pytest_cache
plugins: cov-4.1.0, mock-3.12.0
collected 2 items                                                                                                                                                                        
test_model_config.py::test_register_model_with_batch_size PASSED …
```
> disabling flaky test

- examples/large_models/gpt_fast/handler.py
Creating PR to update the handler for the GPT Fast example to support obtaining the GPU ID from context. 
**Testing:**
Created two model artifacts i.e. `gpt_fast_7b.mar` (4 workers without tensor parallelism) and `gpt_fast_7b_tp.mar` (1 worker with tensor parallelism and parallel level 4) with modified handler. Performed inference with both models:
- **Case 1**: `gpt_fast_7b.mar`
- Command to start TorchServe and perform inference with curl:
```
torchserve --start --ncs --model-store model_store --models gpt_fast_7b.mar
curl "http://localhost:8080/predictions/gpt_fast_7b" -T request.json
``` 
Output:
```
is Paris. It is located in the northern central …
```
> Update GPT Fast handler to add option to get GPU ID from context

- docker/docker_nightly.py
There is a bug in the nightly docker build script where torchserve nightly is being used only for CPU and not GPU images.
Fixes #(issue)
- Before
- After
> Build torchserve nightly GPU image with torchserve nightly

- test/pytest/test_example_gpt_fast.py
- test/pytest/test_send_intermediate_prediction_response.py
Add separate e2e test for send_intermediate_prediction_response
Additionally, it enables streaming in gpt-fast example test
```
======================================================================================= test session starts =======================================================================================
platform linux -- Python 3.10.13, pytest-7.3.1, pluggy-1.3.0
plugins: mock-3.12.0, cov-4.1.0
collected 2 items
test/pytest/test_send_intermediate_prediction_response.py …
```
> Add separate e2e test for send_intermediate_prediction_response

- examples/large_models/gpt_fast/handler.py
- kubernetes/kserve/examples/gpt_fast/Dockerfile
- kubernetes/kserve/examples/gpt_fast/README.md
- kubernetes/kserve/examples/gpt_fast/llama2_v1_gpu.yaml
- kubernetes/kserve/examples/gpt_fast/sample_text.json
- requirements/torch_common.txt
This PR demonstrates how to serve large language models using KServe
- This also shows how to build a custom KServe image for using GPT-Fast
Fixes #(issue)
```
Defaulted container "kserve-container" out of: kserve-container, queue-proxy, storage-initializer (init)
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
2024-01-12T18:25:14,992 [WARN ] main org.pytorch.serve.util.ConfigManager - Your torchserve instance can access any URL to load models. When deploying to production, make sure to limit the set of allowed_urls in config.properties
2024-01-12T18:25:14,996 [INFO ] main org.pytorch.serve.servingsdk.impl.PluginsManager - Initializing plugins manager...
2024-01-12T18:25:15,164 [INFO ] main …
```
> KServe gpt-fast example

- ts/torch_handler/base_handler.py
Use `inference_mode` instead of `no_grad` for `BaseHandler`. It should bring a (small?) performance boost.
Though, I have 2 questions:
* What's the min supported PyTorch version? Because `inference_mode` is supported since PT 1.9.
* Should other handlers (including example ones) be changed as well?
> Use `inference_mode` instead of `no_grad`

- cpp/CMakeLists.txt
- cpp/build.sh
- cpp/src/backends/CMakeLists.txt
- cpp/src/examples/CMakeLists.txt
- cpp/src/utils/CMakeLists.txt
Fixes #(issue)
- Test
```
cd serve/cpp
./build.sh
......
cd _build/src
find . -name "*.dylib"
./backends/libts_backends_protocol.dylib
./backends/libts_backends_core.dylib
./utils/libfoo.dylib
./utils/libts_utils.dylib …
```
> Fix partial compile error on mac x86

- frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
- test/pytest/test_snapshot.py
- ts_scripts/mar_config.json
This PR fixes an issue when a model has no runtime set in the snapshot and we load with a newer torchserve version which expects the field.
Fixes #(issue)
- 
> Fix set model state if runtime is null

- cpp/README.md
- examples/cpp/aot_inductor/llama2/README.md
- examples/cpp/babyllama/README.md
- examples/cpp/llamacpp/README.md
Fixes dead links in cpp documentation
Fixes #(issue)
> Fix dead links in cpp docs

- .github/workflows/benchmark_nightly.yml
- .github/workflows/ci_cpu.yml
- .github/workflows/ci_gpu.yml
- .github/workflows/codeql.yml
- .github/workflows/doc-automation.yml
- .github/workflows/docker-nightly-build.yml
- .github/workflows/kserve_cpu_tests.yml
- .github/workflows/lint.yml
- .github/workflows/official_release_docker.yml
- .github/workflows/regression_tests_cpu.yml
- .github/workflows/regression_tests_gpu.yml
Updating default version of python to 3.9 to be consistent
Fixes #(issue)
N/A
> Update default python version of workflows to 3.9

- examples/large_models/gpt_fast/README.md
- examples/large_models/gpt_fast/handler.py
- examples/large_models/gpt_fast/model_config.yaml
- examples/large_models/gpt_fast/model_config_speculative.yaml
- examples/large_models/gpt_fast/model_config_tp.yaml
- test/pytest/test_example_gpt_fast.py
- ts_scripts/spellcheck_conf/wordlist.txt
This PR enables fxGraphCache in the gpt-fast example to speed up compile time.
Fixes #(issue)
```
===================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.10.12, pytest-7.3.1, pluggy-1.3.0
plugins: mock-3.10.0, cov-4.1.0
collected 5 items / 3 deselected / 2 selected …
```
> Enable fx_graph_cache in gpt-fast example

- README.md
- kubernetes/kserve/tests/scripts/test_mnist.sh
This PR adds the KServe nightly badge to the README
- It also fixes the test logic to clean up port-forwarding
- Passing run: https://github.com/pytorch/serve/actions/runs/7863937837/job/21455109966
Fixes #(issue)
- Passing run: https://github.com/pytorch/serve/actions/runs/7863937837/job/21455109966
> add kserve nightly badge

- ts_scripts/install_dependencies.py
Fixes the build script to use PT nightlies on CPU
Fixes #(issue)
```
python ./ts_scripts/install_dependencies.py --nightly_torch
Collecting numpy                                                                                                                                                                          
Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)                                                                                    
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.5 MB/s eta 0:00:00
Collecting torch …
```
> Enables using PyTorch nightlies on CPU

- .github/workflows/regression_tests_cpu_binaries.yml
Skip running regressions on mac-OS for python 3.8 as onnxruntime has stopped supporting this.
TODO: Need a better system to handle these dependencies
Fixes #(issue)
https://github.com/pytorch/serve/actions/runs/8009451504
> skipping macos regression for python 3.8

- cpp/build.sh
- requirements/torch_cu118_linux.txt
- requirements/torch_cu118_windows.txt
- requirements/torch_cu121_linux.txt
- requirements/torch_cu121_windows.txt
- requirements/torch_darwin.txt
- requirements/torch_linux.txt
- requirements/torch_windows.txt
> Upgrade to PyTorch 2.2.1

- examples/large_models/gpt_fast/README.md
Update to the GPT-Fast example documentation.
Need to pin the commit version.
Fixes #(issue)
```
curl "http://localhost:8080/predictions/gpt_fast" -T request.json
2024-02-26T23:04:59,678 [INFO ] epollEventLoopGroup-3-2 TS_METRICS - ts_inference_requests_total.Count:1.0|#model_name:gpt_fast,model_version:default|#hostname:ip-172-31-11-40,timestamp:1708988699
2024-02-26T23:04:59,679 [DEBUG] W-9000-gpt_fast_1.0 org.pytorch.serve.wlm.WorkerThread - Flushing req.cmd PREDICT repeats 1 to backend at: 1708988699679 …
```
> pin the gpt-fast repo commit version

- kubernetes/kserve/tests/scripts/test_mnist.sh
KServe nightly tests are failing as now KServe is returning the model version too.
Update KServe v2 tests to check the model version too
Seems like this was fixed recently
https://github.com/kserve/kserve/pull/3466
Fixes #([issue](https://github.com/pytorch/serve/issues/2974))
```
MNIST KServe V2 test begin
Deploying the cluster
inferenceservice.serving.kserve.io/torchserve-mnist-v2 created
Waiting for pod to come up...
Check status of the pod
NAME                                                              READY   STATUS    RESTARTS   AGE
torchserve-mnist-v2-predictor-00001-deployment-868bcbc5c6-tv6j4   1/2     Running   0          80s
Name:             torchserve-mnist-v2-predictor-00001-deployment-868bcbc5c6-tv6j4
Namespace:        default …
```
> KServe v2 returns model version now

- cpp/src/backends/process/model_worker.cc
- cpp/src/backends/process/model_worker.hh
This PR fixes a dangling pointer issue in our cpp worker.
Fixes #(issue)
```
curl -v -X POST "http://localhost:8081/models?initial_workers=1&url=llm.mar&batch_size=2&max_batch_delay=5000"
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
> POST /models?initial_workers=1&url=llm.mar&batch_size=2&max_batch_delay=5000 HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.68.0
> Accept: */*
>
2024-02-28T05:23:06,282 [DEBUG] epollEventLoopGroup-3-1 …
```
> Fix dangling pointer error in cpp worker

- ts_scripts/sanity_utils.py
This PR checks links in our doc files in parallel to speed up the process.
> Check links in md files in parallel

- docs/configuration.md
- frontend/server/src/main/java/org/pytorch/serve/metrics/MetricCollector.java
- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
Fixes #(issue)
- Test case1: use TorchServe default system metrics cmd
```
torchserve --ncs --start --model-store model_store
Blacklist Regex: N/A
Maximum Response Size: 6553500
Maximum Request Size: 6553500
Limit …
```
> support system_metrics_cmd in config.properties

- kubernetes/kserve/kserve_wrapper/__main__.py
This PR refactors the properties loading when using the KServe wrapper so that if some configuration elements are missing the defaults defined are used unlike currently where the wrapper fails to start.
This patch also adds ignoring lines starting with a `#` as defined in the properties file format.
Fixes #2994
1. Create models folder
```
mkdir -p /mnt/models/model-store
mkdir -p /mnt/models/config/
```
2. Follow the mnist example but:
- call the model `model` rather than mnist
- set the model store to …
> Make the KServe wrapper configuration loading more resiliant

- ts_scripts/install_dependencies.py
The prescribed way to install torchtext nightly is using cpu nightly binaries, since there are no CUDA binaries for torchtext
Related pytorch [issue](https://github.com/pytorch/pytorch/issues/120156)
Current behavior:
```
INFO: pip is looking at multiple versions of torchtext to determine which version is compatible with other requirements. This could take a while.
Collecting torchtext
Downloading https://download.pytorch.org/whl/nightly/torchtext-0.17.0.dev20240114%2Bcpu-cp39-cp39-linux_x86_64.whl (2.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 5.1 MB/s eta 0:00:00
Downloading https://download.pytorch.org/whl/nightly/torchtext-0.17.0.dev20240113%2Bcpu-cp39-cp39-linux_x86_64.whl (2.0 MB)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 5.1 MB/s eta 0:00:00
Downloading …
```
> Update pytorch nightly installation to use cpu version of torchtext

- .gitmodules
This PR removes the folly submodule which is no longer required to build cpp backend
Fixes #(issue)
> Remove folly submodule

- cpp/README.md
- docker/Dockerfile.cpp
- docker/build_image.sh
- docker/cpp.Dockerfile
```
$ cd docker
$ ./build_image.sh -bt dev -cpp &> docker_build_log.txt
$ docker images
REPOSITORY           TAG           IMAGE ID       CREATED             SIZE
pytorch/torchserve   cpp-dev-cpu   f34040597fea   About an hour ago   1.68GB
```
[docker_build_log.txt](https://github.com/pytorch/serve/files/14517505/docker_build_log.txt)
```
$ cd docker
$ ./build_image.sh -bt dev -g -cv cu121 -cpp &> docker_build_gpu_log.txt
$ docker images
REPOSITORY           TAG                               IMAGE ID       CREATED          SIZE
pytorch/torchserve   cpp-dev-gpu                       539b7b503ccb   51 minutes ago   10.2GB
```
[docker_build_gpu_log.txt](https://github.com/pytorch/serve/files/14544569/docker_build_gpu_log.txt)
Fixes #2908
```
$ docker images
REPOSITORY           TAG …
```
> Enable building dev docker image with CPP backend support

- cpp/build.sh
- cpp/src/backends/core/backend.cc
- cpp/src/examples/CMakeLists.txt
- examples/cpp/aot_inductor/bert/CMakeLists.txt
- examples/cpp/aot_inductor/llama2/CMakeLists.txt
- examples/cpp/aot_inductor/resnet/CMakeLists.txt
- examples/cpp/babyllama/CMakeLists.txt
This PR moves file preparation for cpp backend into cmake which will enable removal of build.sh.
```torchserve_cpp build is complete. To run unit test:   ./_build/test/torchserve_cpp_test
Running main() from /home/ubuntu/serve/cpp/_build/_deps/googletest-src/googletest/src/gtest_main.cc
[==========] Running 49 tests from 12 test suites.
[----------] Global test environment set-up.
[----------] 1 test from BackendIntegTest
[ RUN      ] BackendIntegTest.TestOTFProtocolAndHandler
[       OK ] …
```
> Move file prep from build.sh to cmake

- .github/workflows/kubernetes_tests.yml
- .gitmodules
- README.md
- kubernetes/tests/configs/deployment.yaml
- kubernetes/tests/docker/Dockerfile
- kubernetes/tests/docker/config.properties
- kubernetes/tests/scripts/test_mnist.sh
Workflow for running nightly Kubernetes tests
Passing [run](https://github.com/pytorch/serve/actions/runs/8254810324/job/22579810555)
In addition to functionality test, this PR also checks the performance in terms of CPU usage in a k8s pod. This is important to prevent CPU throttling in a Kubernetes setup with [limits](https://www.datadoghq.com/blog/kubernetes-cpu-requests-limits/)
To do this test, we disable system gpu metrics(because there is higher CPU usage with system GPU metrics enabled) and check the cpu usage when no model is loaded in TorchServe
Fixes #(issue)
Passing run is attached
> Workflow for nightly kubernetes tests

- examples/pt2/README.md
- ts_scripts/spellcheck_conf/wordlist.txt
Readme changes only for adding links for AOTInductor CPP examples to the PT2 readme
> Update PT2 examples readme

- SECURITY.md
Hi, I'm Diogo from [GOSST](https://github.com/diogoteles08#about-gosst-ghost) and I've created this [issue](https://github.com/pytorch/pytorch/issues/120530) and this [PR](https://github.com/pytorch/pytorch/pull/120531) to pytorch/pytorch to enhance their security policy with some security guidelines for users. As discussed in the PR with @malfet, some of the purposed guidelines fit better on pytorch/serve than on pytorch/pytorch, so I'm bringing them here to  ask if they make sense to you.
As your Security Policy already have some (pretty nice) guidelines, I've adapted my suggestion to just append it to your current guidelines (you can find the original sugestion I made them in this [link](https://github.com/diogoteles08/pytorch/blob/331408d05411e76e848694b9e0ab8109e220b04b/SECURITY.md)). …
> Update Security Policy with extra security recommendations

- examples/image_segmenter/deeplabv3/model.py
- examples/image_segmenter/fcn/model.py
- examples/text_to_speech_synthesizer/waveglow_model.py
1. For TorchVision models, pretrained parameters have been deprecated in favor of "Multi-weight support API" - see https://pytorch.org/vision/0.15/models.html
2. `torch.qr` updated to `torch.linalg.qr`
Found with https://github.com/pytorch-labs/torchfix/
Also applied pre-commit to pass linter.
This should be a no-op.
> Update deprecated TorchVision and PyTorch APIs

- docker/Dockerfile
- docker/README.md
- docker/build_image.sh
This PR allows the user to build TorchServe from source from 
- a specific branch and build TS from source
- Build TS from source with Local changes 
Fixes #([issue](https://github.com/pytorch/serve/issues/3054))
```
./build_image.sh -s -l -t pytorch/ts:latest
[+] Building 317.5s (28/28) FINISHED                                                                                                                                       docker:default
=> [internal] load build definition from Dockerfile                                                                                                                                 0.0s
=> => transferring dockerfile: 9.62kB …
```
> Install from source for a specific branch with docker

- .github/workflows/kserve_cpu_tests.yml
- kubernetes/kserve/requirements.txt
KServe nightlies are failing because of KServe's dependency on Ray Serve.
This PR downgrades the version of rayserve as suggested by KServe team , which fixes the problem
Fixes #([issue](https://github.com/pytorch/serve/issues/3044))
```
model-server@41267f0551c9:~$ pip list | grep -i serve
kserve                          0.12.0
torchserve-nightly              2024.4.8
model-server@41267f0551c9:~$ pip list | grep -i ray  
ray                             2.10.0
model-server@41267f0551c9:~$ exit
exit
Traceback (most recent …
```
> Workaround for kserve nightly failure

- docker/config.properties
- docs/configuration.md
- docs/grpc_api.md
- frontend/server/src/main/java/org/pytorch/serve/ModelServer.java
- frontend/server/src/main/java/org/pytorch/serve/util/ConfigManager.java
In the current implementation, the configured GRPC port is by default associated with the wildcard address
https://github.com/pytorch/serve/blob/cdba0fd449c2fd23dcf37c54c0784035541d5114/frontend/server/src/main/java/org/pytorch/serve/ModelServer.java#L450
```
$ torchserve --ncs --start --model-store ./model-store
$ netstat -an | grep 7070
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)
tcp46      0      0  *.7070                 *.*                    LISTEN
$ netstat -an | grep 7071
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)
tcp46      0      0  *.7071                 *.*                    LISTEN
```
Note that the grpc ports `7070` and `7071` are associated with the wildcard address `*`.
With the fix in this PR, the grpc ports …
> Fix GRPC address assignment to localhost by default

- .github/workflows/regression_tests_docker.yml
- test/pytest/test_torch_export.py
Currently `torch._export.aot_load` inference doesn't work in docker. 
It looks like it needs the other other cubin files created at the time of generation of the .so file
This PR also enables docker regressions to be run based on label `docker`
Passing Run: https://github.com/pytorch/serve/actions/runs/8853483743/job/24314425401
Fixes #(issue)
> disable torch export test in docker

- examples/image_classifier/resnet_18/README.md
Adding an example for TorchServe to use `torch.compile` for a `Resnet18` model, similar to what already exists for `densenet161`.
TorchServe start logs from running:
`torchserve --start --model-store model_store --models resnet-18=resnet-18.mar --ts-config config.properties`
```
2024-05-02T16:15:39,305 [INFO ] main org.pytorch.serve.ModelServer - Loading initial models: resnet-18.mar
2024-05-02T16:15:40,423 [INFO ] main org.pytorch.serve.wlm.ModelManager - Model resnet-18 loaded.
2024-05-02T16:15:40,551 [INFO ] main org.pytorch.serve.ModelServer - Initialize Inference server with: EpollServerSocketChannel.
2024-05-02T16:15:41,438 [INFO ] main org.pytorch.serve.ModelServer - Inference API bind to: http://localhost:8443
2024-05-02T16:15:41,438 [INFO ] main org.pytorch.serve.ModelServer - …
```
> Resnet18 torch.compile example

- examples/large_models/gpt_fast_mixtral_moe/README.md
- examples/large_models/gpt_fast_mixtral_moe/model_config.yaml
- examples/large_models/gpt_fast_mixtral_moe/model_config_tp.yaml
- examples/large_models/gpt_fast_mixtral_moe/request.json
Integrate gpt-fast mixtral/moe example in TorchServe.
Model inference(int8 quantized tensor paralleled Mixtral-MOE) logs provided in the attachment file.
[mixtral_moe_logs.txt](https://github.com/pytorch/serve/files/15389579/mixtral_moe_logs.txt)
> GPT-FAST-MIXTRAL-MOE integration

- benchmarks/models_config/bert_torch_compile_gpu.yaml
Changing mar file for Bert torch compile so that it includes `torch.inference_mode()`
> Changing mar file for Bert torch compile

- .github/workflows/kubernetes_tests.yml
- benchmarks/utils/system_under_test.py
- kubernetes/tests/scripts/test_mnist.sh
Adding `--model-api-enabled` flag to nightly benchmark tests to ensure they run
Adding `model_api_enabled=true` to kubernetes nightly test 
Test: [Kubernetes nightly test](https://github.com/pytorch/serve/actions/runs/9488203897)
> Updating night CIs to account for model control 

- .github/workflows/docker-ci.yaml
- docker/build_image.sh
- docker/dockerd-entrypoint.sh
- docker/test_container_model_prediction.sh
Current Docker CI is using latest TorchServe release rather then the branch that is being merged in. 
Fix by using the `-s ` and `-r` flag that will build TorchServe from the source and use the local branch. 
Also adding '--disable-token` flag for the docker tests to run properly.
> Fixing docker CI 

- examples/image_classifier/densenet_161/README.md
- examples/image_classifier/densenet_161/model-config.yaml
Update image_classifier/densenet-161 to include torch.compile
Add model config file
Update README
- TorchServe starts logs
```
2024-06-21T15:16:28,320 [INFO ] W-9035-densenet161_1.0-stdout MODEL_LOG - [PID]3640610
2024-06-21T15:16:28,320 [INFO ] W-9002-densenet161_1.0-stdout MODEL_LOG - Python runtime: 3.12.2
2024-06-21T15:16:28,320 [INFO ] W-9035-densenet161_1.0-stdout MODEL_LOG - Torch worker started.
2024-06-21T15:16:28,320 [INFO ] W-9011-densenet161_1.0-stdout MODEL_LOG - Torch worker started.
```
- Output prediction
```
{
"tabby": 0.4664836823940277,
"tiger_cat": 0.4645617604255676,
"Egyptian_cat": 0.06619937717914581,
"lynx": 0.0012969186063855886,
"plastic_bag": 0.00022856894065625966
}
```
> Update image_classifier/densenet-161 to include torch.compile

- .github/workflows/kserve_cpu_tests.yml
- kubernetes/kserve/requirements.txt
Current pinned version of ray is causing dependency issues with newer version of setuptools. Solution is to unpin ray and test to see if the newer release of ray will work.
> Kserve fix ray & setuptools dependency issue

- requirements/developer.txt
Reverts pytorch/serve#3171
twine upload fails https://github.com/pytorch/serve/actions/runs/9678681051
> Revert "Bump twine from 4.0.2 to 5.1.0"

- examples/image_classifier/vgg_16/README.md
- examples/image_classifier/vgg_16/model-config.yaml
Update image_classifier/vgg-16 to include torch.compile
Add model config file
Update README
Verified output for a sample inference call makes sense before and after using a model config file
> Update documentation for vgg16 to use torch.compile

- docker/Dockerfile
- docker/build_image.sh
Torchserve docker build with remote branch needs to copy the remote version of entrypoint (`dockerd-entrypoint.sh`) to the image to keep it consistent with the `--branch_name` specified for the build.
Fixes #(issue)
We encountered this issue where the torchserve image is expected from --branch_name v0.11.0 in order to work with pinned torchserve pypi package version, but the current entrypoint is out-of-sync and uses additional flag `--disable-token` from master.
Re-run `bash ./build_image.sh --branch_name v0.11.0 --pythonversion 3.10 --tag test-image` to verify that the newly built image now has `/usr/local/bin/dockerd-entrypoint.sh` from branch v0.11.0 without `--disable-token` set. 
```
% docker run --rm -it --entrypoint bash test-image …
```
> Copy remote branch entrypoint to compile and production image stages

- ts/torch_handler/base_handler.py
#3132 and #3141 introduced support for Intel GPU devices, but the condition checking [here](https://github.com/pytorch/serve/blob/master/ts/torch_handler/base_handler.py#L161) might cause problems for versions without torch.xpu. This PR fixed it.
> Fix Condition Checking for Intel GPUs Enabling

- README.md
wasn't rendering correctly
Fixes #(issue)
> fix broken llm deployment link

- requirements/common.txt
Removes dependency on vllm to avoid docker size bloat.
This will be addressed after the 0.11.1 release
Fixes #([issue](https://github.com/pytorch/serve/issues/3244))
> Remove vllm dependency to not bloat docker image size

- .github/workflows/kserve_cpu_tests.yml
- kubernetes/kserve/requirements.txt
Removing the pinned dependency on setuptools
Fixes #([issue](https://github.com/pytorch/serve/pull/3241))
> Upgrade kserve dependencies

- examples/image_classifier/resnet_152_batch/README.md
Adding an example for TorchServe to use `torch.compile` for a batch `Resnet152` model, similar to what already exists for `densenet161`.
- The documentation of batched `Resnet152` was updated.
I executed the instructions that are added with this pull request.
> Resnet152 batch inference torch.compile example

- examples/stateful/sequence_batching/Readme.md
- examples/stateful/sequence_continuous_batching/Readme.md
- frontend/archive/src/main/java/org/pytorch/serve/archive/model/ModelConfig.java
- frontend/server/src/main/java/org/pytorch/serve/http/messages/DescribeModelResponse.java
- frontend/server/src/main/java/org/pytorch/serve/job/JobGroup.java
- frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/Model.java
- frontend/server/src/main/java/org/pytorch/serve/wlm/SequenceBatching.java
- model-archiver/README.md
- test/pytest/test_example_stateful_sequence_continuous_batching_http.py
- ts_scripts/spellcheck_conf/wordlist.txt
Add support for session timeout for stateful inference.
`sequenceTimeoutMSec`: the max duration in milliseconds of a sequence inference request of this stateful model. The default value is 0 (ie. there is effectively no sequence timeout and the sequence does not expire). TorchServe does not process a new inference request if the sequence timeout is exceeded.
> Implement stateful inference session timeout

- frontend/server/src/main/java/org/pytorch/serve/job/GRPCJob.java
Leave `response` and `sendError` method when `responseObserver` is canceled to avoid continuing on canceled requests.
This was the previous behavior introduced by #2420 and lost during a later refactoring. A similar early return on cancel exists for case `OIPPREDICT` in `response` method.
Fixes #3087 
To my knowledge, there is no dedicated tests for this issue (it was fixed before and then reintroduced).
Currently trying to figure out how to properly test it.
> Leave response and sendError when request is canceled

- examples/pt2/torch_compile_hpu/README.md
We'd like to remove the note as some options are unsupported, what can be misleading.
> Remove compile note for hpu

- examples/image_classifier/squeezenet/README.md
Adding a TorchServe example using `torch.compile` for a squeezenet model.
N/A, doc change made, validated by running inference as described in the added sections
> squeezenet torch.compile example

- .github/workflows/kserve_cpu_tests.yml
- .github/workflows/kserve_gpu_tests.yml
- kubernetes/kserve/tests/configs/mnist_v1_gpu.yaml
- kubernetes/kserve/tests/configs/mnist_v2_gpu.yaml
- kubernetes/kserve/tests/scripts/test_mnist.sh
> add kserve gpu tests

- examples/large_models/utils/test_llm_streaming_response.py
- examples/large_models/vllm/llama3/Readme.md
- examples/large_models/vllm/llama3/chat.json
- examples/large_models/vllm/llama3/model-config.yaml
- examples/large_models/vllm/llama3/prompt.json
- examples/large_models/vllm/lora/Readme.md
- examples/large_models/vllm/lora/model-config.yaml
- examples/large_models/vllm/lora/prompt.json
- examples/large_models/vllm/mistral/Readme.md
- examples/large_models/vllm/mistral/model-config.yaml
- examples/large_models/vllm/mistral/prompt.json
- frontend/server/src/main/java/org/pytorch/serve/http/api/rest/InferenceRequestHandler.java
- test/pytest/test_example_vllm.py
- test/pytest/test_url_path.py
- ts/torch_handler/vllm_handler.py
- ts_scripts/spellcheck_conf/wordlist.txt
This PR enables OpenAI compatible api for vllm integration.
It removes the previous undefined interface for llms served through vllm engine.
New interface can be used like OpenAI endpoint:
Curl:
```bash
curl --header "Content-Type: application/json"   --request POST   --data @prompt.json http://localhost:8080/predictions/llama-8b-lora/1.0/v1/completions
```
Python + Request:
```bash
python ../../utils/test_llm_streaming_response.py -m llama-8b-lora -o 50 -t 2 -n 4 --prompt-text "@prompt.json" --prompt-json --openai-api --demo-streaming
```
OpenAI client:
```python
from openai import OpenAI
model_name = "llama-8b-lora"
stream=True
openai_api_key = "EMPTY"
openai_api_base = f"http://localhost:8080/predictions/{model_name}/1.0/v1"
client = OpenAI(
api_key=openai_api_key, …
```
> Feature add openai api for vllm integration

- examples/Huggingface_Transformers/Transformer_handler_generalized.py
Typo fixes in docstrings and comments.
I noticed these while reading the code so thought I would open a quick PR.
Note once change from Summarises -> Summarizes. While the first isn't wrong per se (British English vs. American English), it doesn't match the spelling in the actual function name.
Fixes #(issue)
Just typo fixes
No testing as just typo fixes.
> typo fixes in HF Transformers example

- model-archiver/model_archiver/model_packaging_utils.py
This PR fixes the wild card feature in the model archiver
Fixes #(issue)
```
(serve) ubuntu@ip-172-31-55-226:~/serve$ mkdir extras
(serve) ubuntu@ip-172-31-55-226:~/serve$ touch extras/test1.txt
(serve) ubuntu@ip-172-31-55-226:~/serve$ touch extras/test2.txt
(serve) ubuntu@ip-172-31-55-226:~/serve$ torch-model-archiver --model-name mnist --version 1.0 --model-file examples/image_classifier/mnist/mnist.py --serialized-file examples/image_classifier/mnist/mnist_cnn.pt --handler  examples/image_classifier/mnist/mnist_handler.py …
```
> Fix wild card in extra files

- ts/torch_handler/vllm_handler.py
This PR changes the vllm method to create their workers from fork to spawn to avoid an issue where vllm tries to reinitialize the CUDA context
> Set vllm multiproc method to spawn

- examples/custom_endpoint_plugin/ModelReady.java
- examples/custom_endpoint_plugin/README.md
- examples/custom_endpoint_plugin/org.pytorch.serve.servingsdk.ModelServerEndpoint
- plugins/endpoints/build.gradle
- plugins/endpoints/src/main/resources/META-INF/services/org.pytorch.serve.servingsdk.ModelServerEndpoint
Add an example to demonstrate building a custom endpoint plugin which reports model ready status to serve inference requests.
> Example to demonstrate building a custom endpoint plugin

- .github/workflows/benchmark_nightly.yml
> Benchmark fix

- docs/Troubleshooting.md
- docs/custom_service.md
PR #3071 moved the location of the `WaveGlow` files. This PR adjusts sources to changes.
> docs: update WaveGlow links

- frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java
- frontend/server/src/main/resources/proto/management.proto
- frontend/server/src/test/resources/management_open_api.json
- frontend/server/src/test/resources/model_management_api.json
Simple typo fix in the openapi specs:
- "a asynchronous" -> "an asynchronous"
- Insert space between two sentences
- Add period at the end of some sentences
n/a
> Fix typo: "a asynchronous" -> "an asynchronous"

- benchmarks/utils/system_under_test.py
Fixes #(issue)
```
python ./benchmarks/benchmark-ab.py --tmp_dir /tmp --report_location /tmp --config_properties ./benchmarks/config.properties --config /home/ubuntu/actions-runner/_work/serve/serve/model_json_config/neu …
```
> Clear up neuron cache

- examples/large_models/utils/test_llm_streaming_response.py
- frontend/server/src/main/java/org/pytorch/serve/openapi/OpenApiUtils.java
- frontend/server/src/main/java/org/pytorch/serve/util/ApiUtils.java
- frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
- frontend/server/src/test/resources/management_open_api.json
- frontend/server/src/test/resources/model_management_api.json
Hi, thank you for merging my previous PR. This is yet another typo fix PR. What it does is:
- `vesion` -> `version`
- `succsesfully` -> `successfully`
n/a
> Fix typo: vesion -> version, succsesfully -> successfully

- README.md
- ts/llm_launcher.py
Adding a variable `model_snapshot_path` to `None` should resolve the error introduced in the following issue.
Fixes #([3335](https://github.com/pytorch/serve/issues/3335))
> set model_snapshot_path to None to prevent unbound local error

- examples/usecases/llm_diffusion_serving_app/README.md
Updated links in the README for proper HTML docs generation in the Multi-Image generation usecase app .
> Update README.md for Multi-Image generation usecase app 

- frontend/server/src/main/java/org/pytorch/serve/device/utils/AppleUtil.java
- frontend/server/src/test/java/org/pytorch/serve/ModelServerTest.java
- frontend/server/src/test/java/org/pytorch/serve/device/utils/AppleUtilTest.java
- frontend/server/src/test/java/org/pytorch/serve/util/ConfigManagerTest.java
- ts/metrics/system_metrics.py
Backend system metrics lacks support for `torch.mps` accelerator devices. This PR will add those changes and modify frontend code to handle Apple M1 GPU as single accelerator device to fix issues with frontend tests and make Accelerator class definition to be more consistent across hardware vendors.
Fixes #3376
```
> ./frontend/gradlew -p frontend clean build
...
BUILD SUCCESSFUL
```
> Add Apple system metrics support

- .github/workflows/lint.yml
The tags in tj-actions/changed-files action are compromised and are leaking GitHub secrets in repos using the compromised repo. This pins the action to a known good hash.
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
> Tags in tj-actions/changed-files are compromised
